### ISSUE TITLE
VS2010: pcm-core.cpp

### ISSUE THREAD

**Issue by Skysnakes** [opcm/pcm#10]
ERROR	21	error C2059: Syntaxerror: ')'		70	1	pcm-core-win
ERROR	29	error C2059: Syntaxerror: ')'		110	1	pcm-core-win

It seems that there is a problem with the include paths or something like that, since VS2010 highlight, that <iostream> etc. are not available. I don't really know, what the problem is, since I use in general Linux and make, cmake or something like that and not VisualStudio on Windows.

I just want to compile the project to thest it with my i7-920 CPU to see, if it works fine with games. 

I also tried the precompiled binaries, but it seems, that the don't work.

**Comment by opcm** [comment]
Hi,

I don't have VS2010 to reproduce. I am not sure how if I would be able to support this.

Could you please be more specific what did not work with the pre-compiled binaries (https://ci.appveyor.com/project/opcm/pcm/build/artifacts) ? Any error messages?

Thank you

**Comment by opcm** [comment]
It seems you have fixed the issue here: https://github.com/opcm/pcm/issues/9
If the issue still exists please re-open it.

**Comment by bvid34tgd** [comment]
[license.zip](https://github.com/intel/pcm/files/15319605/license.zip)
just ok
