### ISSUE TITLE
pcm does not work with secure boot

### ISSUE THREAD

**Issue by etsaur4** [opcm/pcm#102]
While using secure boot, PCM returns zeros, but perf still works.

# perf stat -e uncore_imc_1/cas_count_read/ -I 1000 -a
#           time             counts unit events
     1.000132123               1.67 MiB  uncore_imc_1/cas_count_read/                                  
     2.000226366               0.91 MiB  uncore_imc_1/cas_count_read/                                  
     3.000350818               2.66 MiB  uncore_imc_1/cas_count_read/                                  
     4.000489773               2.84 MiB  uncore_imc_1/cas_count_read/                                  
...
 Secure Boot Enabled
===================
 |---------------------------------------||---------------------------------------|
|--             Socket  0             --||--             Socket  1             --|
|---------------------------------------||---------------------------------------|
|--     Memory Channel Monitoring     --||--     Memory Channel Monitoring     --|
|---------------------------------------||---------------------------------------|
|-- NODE 0 Mem Read (MB/s) :     0.00 --||-- NODE 1 Mem Read (MB/s) :     0.00 --|
|-- NODE 0 Mem Write(MB/s) :     0.00 --||-- NODE 1 Mem Write(MB/s) :     0.00 --|
|-- NODE 0 P. Write (T/s):          0 --||-- NODE 1 P. Write (T/s):          0 --|
|-- NODE 0 Memory (MB/s):        0.00 --||-- NODE 1 Memory (MB/s):        0.00 --|
|---------------------------------------||---------------------------------------|
|---------------------------------------||---------------------------------------|
|--                 System Read Throughput(MB/s):          0.00                --|
|--                System Write Throughput(MB/s):          0.00                --|
|--               System Memory Throughput(MB/s):          0.00                --|
|---------------------------------------||---------------------------------------|

 Secure Boot Disabled
====================
|---------------------------------------||---------------------------------------|
|--             Socket  0             --||--             Socket  1             --|
|---------------------------------------||---------------------------------------|
|--     Memory Channel Monitoring     --||--     Memory Channel Monitoring     --|
|---------------------------------------||---------------------------------------|
|-- Mem Ch  0: Reads (MB/s):     0.62 --||-- Mem Ch  0: Reads (MB/s):     0.60 --|
|--            Writes(MB/s):     0.56 --||--            Writes(MB/s):     0.57 --|
|-- Mem Ch  1: Reads (MB/s):     0.57 --||-- Mem Ch  1: Reads (MB/s):     0.59 --|
|--            Writes(MB/s):     0.52 --||--            Writes(MB/s):     0.56 --|
|-- Mem Ch  2: Reads (MB/s):     0.56 --||-- Mem Ch  2: Reads (MB/s):     0.59 --|
|--            Writes(MB/s):     0.52 --||--            Writes(MB/s):     0.56 --|
|-- Mem Ch  3: Reads (MB/s):     0.55 --||-- Mem Ch  3: Reads (MB/s):     0.65 --|
|--            Writes(MB/s):     0.52 --||--            Writes(MB/s):     0.65 --|
|-- Mem Ch  4: Reads (MB/s):     0.56 --||-- Mem Ch  4: Reads (MB/s):     0.68 --|
|--            Writes(MB/s):     0.52 --||--            Writes(MB/s):     0.68 --|
|-- Mem Ch  5: Reads (MB/s):     0.54 --||-- Mem Ch  5: Reads (MB/s):     0.66 --|
|--            Writes(MB/s):     0.50 --||--            Writes(MB/s):     0.66 --|
|-- NODE 0 Mem Read (MB/s) :     3.40 --||-- NODE 1 Mem Read (MB/s) :     3.77 --|
|-- NODE 0 Mem Write(MB/s) :     3.15 --||-- NODE 1 Mem Write(MB/s) :     3.69 --|
|-- NODE 0 P. Write (T/s):      37643 --||-- NODE 1 P. Write (T/s):      37645 --|
|-- NODE 0 Memory (MB/s):        6.55 --||-- NODE 1 Memory (MB/s):        7.46 --|
|---------------------------------------||---------------------------------------|
|---------------------------------------||---------------------------------------|
|--                 System Read Throughput(MB/s):          7.16                --|
|--                System Write Throughput(MB/s):          6.84                --|
|--               System Memory Throughput(MB/s):         14.00                --|
|---------------------------------------||---------------------------------------|

**Comment by opcm** [comment]
which Linux distribution are you using? could you please send the out put of these commands:
uname -a
cat /etc/os-release

Thanks

**Comment by etsaur4** [comment]
sorry for the long delay.
This was on Oracle Linux
uname -a
Linux scaqai01adm08.us.oracle.com 4.14.35-1851.el7uek.x86_64 #2 SMP Mon Dec 17 23:45:32 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

This is mostly inline with upstream kernel 4.18/4.19.

/etc/os-release
NAME="Oracle Linux Server"
VERSION="7.5"
ID="ol"
VERSION_ID="7.5"
PRETTY_NAME="Oracle Linux Server 7.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.5

**Comment by opcm** [comment]
the upstream kernel does not block MSR writes on secure boot: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/x86/kernel/msr.c?h=linux-4.19.y

I failed to find the Oracle version of the linux kernel. Here (https://oss.oracle.com/sources/ and https://oss.oracle.com/ol7/SRPMS-updates/) I only found 3.10 based kernel sources.

Could you please help me find the sources for 4.14 derivatives? 

I wonder if one can set CAP_COMPROMISE_KERNEL (or similar) capability to PCM binary to make it work.

Thanks

**Comment by etsaur4** [comment]
Hi, figured out why there is a discrepancy.
OL, Redhat, CentOS and Fedora all applied secure boot patches that Linus has not allowed in, which blocks MSR accesses from userland.

https://linux-git.us.oracle.com/UEK/linux-uek5/commit/218d4c96ef6483d4f1fb5ce556e4f406d0143ca8

I can't get you the latest OL code, but I suspect older OL have the same issue as well as Redhad, Centos and Fedora.

**Comment by opcm** [comment]
the link is not accessible...

**Comment by etsaur4** [comment]
Sorry, I pointed to an internal site.
It's pretty much this patch

http://kernsec.org/pipermail/linux-security-module-archive/2018-April/006396.html\\

 arch/x86/kernel/msr.c |   10 ++++++++++
 1 file changed, 10 insertions(+)

diff --git a/arch/x86/kernel/msr.c b/arch/x86/kernel/msr.c
index ef688804f80d..dfb61d358196 100644
--- a/arch/x86/kernel/msr.c
+++ b/arch/x86/kernel/msr.c
@@ -84,6 +84,11 @@ static ssize_t msr_write(struct file *file, const char __user *buf,
 	int err = 0;
 	ssize_t bytes = 0;
 
+	if (kernel_is_locked_down("Direct MSR access")) {
+		pr_info("Direct access to MSR %x\n", reg);
+		return -EPERM;
+	}
+
 	if (count % 8)
 		return -EINVAL;	/* Invalid chunk size */
 
@@ -135,6 +140,11 @@ static long msr_ioctl(struct file *file, unsigned int ioc, unsigned long arg)
 			err = -EFAULT;
 			break;
 		}
+		if (kernel_is_locked_down("Direct MSR access")) {
+			pr_info("Direct access to MSR %x\n", regs[1]); /* Display %ecx */
+			err = -EPERM;
+			break;
+		}
 		err = wrmsr_safe_regs_on_cpu(cpu, regs);
 		if (err)
 			break;

**Comment by opcm** [comment]
thanks for the link. PCM already supports programming events on PMUs in the core using Linux perf driver. I will look into support of uncore metrics in PCM through Linux perf driver as well to make it work with secure boot.

**Comment by opcm** [comment]
I just pushed changes to PCM master branch that should make it work. Please test.

**Comment by etsaur4** [comment]
Thank you, I  confirmed it works.

**Comment by opcm** [comment]
great to hear
