### ISSUE TITLE
PCM::checkCustomCoreProgramming fails (probably a data race??)

### ISSUE THREAD

**Issue by soramichi** [opcm/pcm#106]
The newly introduced `PCM::checkCustomCoreProgramming` function yields something like this when I run `pcm.x`.

```
...
PCM Error: someone has corrupted custom counter 0 on core 1 expected value 43412e value read 4308d2
PCM Error: someone has corrupted custom counter 1 on core 1 expected value 4308d2 value read 4307d2
PCM Error: someone has corrupted custom counter 2 on core 1 expected value 4307d2 value read 4302d1
PCM Error: someone has corrupted custom counter 3 on core 1 expected value 4302d1 value read 43412e
...
```

This is very weird because the expected value of counter[(i+1)%4] exactly matches the read value of counter[i]. I guess there might be a data race somewhere underneath `msr->read` (for example, is `Rdmsr()` thread safe??), but I could not find the root cause.

It happens on Xeon E5-1603 v4 with Debian 9 (uname -r: `4.9.0-8-amd64`) but it does not happen on Core i5 7500 with Debian testing (uname -r: `4.19.11`). I confirmed to use the same compiler (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) by copying the `pcm.x` binary from the former machine to the latter.

**Update**: Because it does not happen when I comment-out `CXXFLAGS += -DPCM_USE_PERF`, the problem might be in the programming side (reading msrs does not depend on whether or not perf is used). However, the programming side is not multi-threaded and I don't know why this weird thing happens.

I'm happy to provide any further information if it helps.

**Comment by opcm** [comment]
thanks for reporting this! It seems perf does not guarantee the consecutive mapping of events to perfmon counters 0,1,2,3. One needs to figure out how perf event mapping can be retrieved or detected.

As a workaround please use this version: https://github.com/opcm/pcm/releases/tag/201812.3

**Comment by soramichi** [comment]
Makes sense. It seems that the mapping from a fd to the event id could be retrieved by ioctl (haven't tried it, but the manual says something like that).

Search for "PERF_EVENT_IOC_ID" in this page: http://man7.org/linux/man-pages/man2/perf_event_open.2.html

**Comment by opcm** [comment]
I disabled this feature for perf. We can consider the bug as resolved.
