### ISSUE TITLE
pcm-msr sometimes cannot write to MSR on macOS (maybe when a core is sleeping)

### ISSUE THREAD

**Issue by Gumix** [opcm/pcm#110]
Here is an example from Intel Core i5-6267U CPU:
```
$ ./pcm-msr.x -w 0x1234 -c 0 0x680                                                                                              

 Processor Counter Monitor  (2018-12-20 09:35:58 +0100 ID=1390574)

 MSR read/write utility

 Writing 0x1234 to MSR 0x680 on core 0
 Read value 0 from MSR 0x680 on core 0

$ ./pcm-msr.x -w 0x1234 -c 0 0x680

 Processor Counter Monitor  (2018-12-20 09:35:58 +0100 ID=1390574)

 MSR read/write utility

 Writing 0x1234 to MSR 0x680 on core 0
 Read value 0x1234 from MSR 0x680 on core 0
```

MSR 0x680 is MSR_LASTBRANCH_0_FROM_IP, which is R/W and unique per Thread. Last branch recording is stopped (MSR_DEBUGCTL = 0).

I noticed that it succeeds almost every time on cores 0 and 2, while cores 1 and 3 require about 10 attempts to write the value (note that i5-6267U has 2 real cores and 4 threads). Probably pcm-msr is unable to run wrmsr on a core which is in a sleeping state. I tried to load all cores to 100%, in this case pcm-msr works fine.

**Comment by opcm** [comment]
This MSR is special. It may be cleared when the core enters a sleep state > C1 (see section 17.12.3 **"LBR Behavior and Deep C-State"** in https://software.intel.com/en-us/articles/intel-sdm#combined ). The core might sleep between the read and write call to MSR driver.
