### ISSUE TITLE
Disabling QPI counters

### ISSUE THREAD

**Issue by flx42** [opcm/pcm#111]
This code freezes, enables, resets, and unfreezes the QPI PMON registers:
https://github.com/opcm/pcm/blob/bce551dfcdc5fb8360c3ca7acf17b4a5c6c32a13/cpucounters.cpp#L4729-L4766

However, I could not find anywhere in the code were those counters are disabled, i.e. it's not in `cleanupPMU` nor in `resetPMU`.

I have also verified that if I launch `pcm.x` once, then disable the above code, then relaunch `pcm.x`, then the QPI bandwidth is still reported correctly, proof that the counters were still active.

I don't know if I this has any impact on performance, or if there is a simple way to disable the counters; but it would be useful to add this to the API. For now I'll bake my own script with `setpci` for this purpose.

**Comment by opcm** [comment]
there is no impact on performance. The cleanup for uncore PMUs will be implemented soon.

**Comment by opcm** [comment]
this is addressed in the master branch.
