### ISSUE TITLE
Can PCM tools support win10?

### ISSUE THREAD

**Issue by minititanxi** [opcm/pcm#112]
In WinMSRDriver folder,there is only code generate WIN7 driver,Can this tool support win10?

**Comment by opcm** [comment]
yes, Win7 msr driver should also support Win10. Alternatively you can use winring0 driver as described in the Windows HOWTO

**Comment by minititanxi** [comment]
Thank you very much!pcm tool is running perfectly!

**Comment by opcm** [comment]
glad to hear
