### ISSUE TITLE
pcm-sensor.x Ksysguard not reporting L caches

### ISSUE THREAD

**Issue by WilliamTambellini** [opcm/pcm#115]
Compiled on Ubuntu 16 using gcc 5.4.
sudo ./pcm.x seems to work ok:
 Core (SKT) | EXEC | IPC  | FREQ  | AFREQ | L3MISS | L2MISS | L3HIT | L2HIT | L3MPI | L2MPI |  TEMP

   0    0     0.01   0.75   0.02    0.35      97 K    345 K    0.71    0.60    0.00    0.01     55
   1    0     0.01   0.62   0.01    0.33     145 K    318 K    0.54    0.32    0.01    0.01     56
   2    0     0.01   1.54   0.00    0.32      13 K     28 K    0.52    0.57    0.00    0.00     56
   3    0     0.00   0.34   0.00    0.34      16 K     32 K    0.44    0.25    0.01    0.01     56
   4    0     0.00   0.63   0.00    0.31    1792     4803      0.57    0.44    0.00    0.01     55
   5    0     0.00   0.39   0.00    0.32    9940       18 K    0.43    0.51    0.01    0.01     56
   6    0     0.00   0.22   0.00    0.31    4213     7038      0.31    0.28    0.01    0.02     56
   7    0     0.00   0.28   0.00    0.31    6370       11 K    0.37    0.31    0.01    0.01     56

but pcm.sensor.x L caches do seem to report only 0 or 1 to ksysguard : 
sudo ksysguard
"file > new tab"
"monitor remote machine"
custom command
command:  /home/wtambellini/repos/pcm/pcm-sensor.x
drag and dropped L2 or L3 caches miss or hit
but when charting, values are always 0 or 1

**Comment by opcm** [comment]
just pushed a change into the master branch which should help. Please test

**Comment by opcm** [comment]
please reopen if you still see any issues
