### ISSUE TITLE
How to use PCM to measure performance my own code 

### ISSUE THREAD

**Issue by ParkWANG** [opcm/pcm#118]
Hi. I'm trying to use PCM to measure performance my own code, I want to know the memory stall cycles when executing my code. 
I inset PCM like the example I searched but seems not right. 

  PCM * m = PCM::getInstance();
  PCM::ErrorCode returnResult = m->program();
  if (returnResult != PCM::Success)
  { std::cerr << "Intel's PCM couldn't start" << std::endl;
    std::cerr << "Error code: " << returnResult << std::endl;
    exit(1);
  }
  SystemCounterState before_sstate = getSystemCounterState();
    // my code
  SystemCounterState after_sstate = getSystemCounterState();

Can I have your help, if you know.  Seems I need some initialization of PCM

**Comment by opcm** [comment]
The initialization seems to be fine. What code does m->program() return? I suggest to use a more verbose checking procedure such as here: https://github.com/opcm/pcm/blob/master/pcm-latency.cpp#L371

**Comment by opcm** [comment]
Did the new procedure help?

**Comment by opcm** [comment]
please reopen if you still see the issue

**Comment by ParkWANG** [comment]
Thank your. Get solved well with your link.
