### ISSUE TITLE
pcm does not report QPI counters on Windows

### ISSUE THREAD

**Issue by LouisLaborde** [opcm/pcm#119]
On Windows, pcm.exe shows in output "Link <num> is disabled" for all QPI/UPI links on each socket,
and does not report any QPI/UPI statistics.

This is because of these lines in cpucounters.cpp:
        // freeze enable
        if (4 != qpiLLHandles[i]->write32(LINK_PCI_PMON_BOX_CTL_ADDR, extra))

The problem is in pci.cpp where for Windows, PciHandle::write32 does not return 4 upon success, since DeviceIoControl for IO_CTL_PCICFG_WRITE does not return any data and reslength is 0.

Code should be modified as follows:
        BOOL status = DeviceIoControl(hDriver, IO_CTL_PCICFG_WRITE, &req, (DWORD)sizeof(PCICFG_Request), &result, (DWORD)sizeof(uint64), &reslength, NULL);
        if (!status)
        {
            //std::cerr << "Error writing PCI Config space at bus "<<bus<<" dev "<< device<<" function "<< function <<" offset "<< offset << " size "<< req.bytes  << ". Windows error: "<<GetLastError()<<std::endl;
           return 0;
        }
        return (int32)sizeof(uint32);

I tested with this change and was able to get the QPI/UPI statistics.

**Comment by opcm** [comment]
thanks for reporting. Could you please submit your change a pull request?

**Comment by opcm** [comment]
Actually it seems you are testing the old version of PCM where this code has been removed. Could you please check the latest from the master branch if it works for you?

**Comment by LouisLaborde** [comment]
I am testing with the 20181204 NDA version of PCM.
I haven't diff'ed the NDA and the public versions of PCM: what are the differences?

**Comment by opcm** [comment]
the latest PCM version from github master branch already includes all features of your version (incl. Cascade Lake and PMM support).

**Comment by LouisLaborde** [comment]
I tested the latest github version and it does report the QPI/UPI counters on Windows.
Sorry for the disturbance.

**Comment by opcm** [comment]
thanks for reporting and testing! Your suggestion still makes sense to make it comply with the interface requirements of the write32 method.

**Comment by opcm** [comment]
the change will be published soon (but it does not impact any functionality)
