### ISSUE TITLE
Include doxygen in gitignore

### ISSUE THREAD

**Issue by ImmanuelHaffner** [opcm/pcm#12]
Hey, this is just a minor thing. Can you please include the output directories of doxygen in the gitignore file? Thanks & regards.

diff --git a/.gitignore b/.gitignore
index 6f5b269..6f63201 100644
--- a/.gitignore
+++ b/.gitignore
@@ -24,3 +24,5 @@ Release
 Debug64
 Release64
 .metadata/
+html/
+latex/

**Comment by opcm** [comment]
please create a pull request with the patch
