### ISSUE TITLE
PCM execution (w/ external application) doesn't follow OpenMP environment variable

### ISSUE THREAD

**Issue by lucasroges** [opcm/pcm#120]
Hello,

I'm trying to execute some OpenMP applications of the NAS Parallel Benchmarks set with the PCM tool, but as I set or export OMP_NUM_THREADS to a specific number, the executions with PCM always run with 48 threads (maximum number of threads). Is there a way to instrument a specific number of threads to run or even to set some kind of affinity using PCM?

**Comment by opcm** [comment]
I am wondering why you need to restrict affinity for PCM.... Are you running on Linux? On Linux you can use taskset (https://linux.die.net/man/1/taskset) to restrict affinity of a command/process

**Comment by lucasroges** [comment]
Ok, I understand, but my main concern here wasn't actually about affinity, sorry. I'd just like to know why the environment variable isn't working when I run the programs with PCM and how can I fix it or if there is some way to define the number of threads (OpenMP) to run, in the PCM command. And yes, I'm running it on Linux.

**Comment by opcm** [comment]
PCM does not reset OMP_NUM_THREADS or use this variable (it is not using OpenMP). This behavior is new to me. You can also try to put export OMP_NUM_THREADS and the app invocation in a script and start this script from pcm.

**Comment by lucasroges** [comment]
It worked, thanks!

**Comment by lucasroges** [comment]
It worked, thanks!
