### ISSUE TITLE
Can PCM monitor specified application's IPC on windows?

### ISSUE THREAD

**Issue by minititanxi** [opcm/pcm#123]
I want to monitor the specified application's IPC,not the cpu's IPC,
Can PCM make it?
Thank you

**Comment by opcm** [comment]
PCM is a core/CPU centric-tool. The best you can do is to set affinity of the application to certain cores (programmatically or manually https://merabheja.com/set-affinity-for-an-application-on-windows-10/ ) and then monitor these cores using PCM.

best regards,
Roman
