### ISSUE TITLE
Monitor PCIe device bandwidth for Kabylake

### ISSUE THREAD

**Issue by llamafilm** [opcm/pcm#129]
Hello.  I'm using GPUs over Thunderbolt 3 on a Mac Mini and I suspect the bus is saturated.  I was hoping to measure this with pcm-iio.x but it says only Skylake is supported.  And pcm-pcie-x only supports Jaketown, Ivytown, Haswell, Broadwell-DE.  It would be great to add support for Kabylake and others.

**Comment by opcm** [comment]
Kabylake does not have a hardware performance monitoring unit that PCM can query for PCIe bandwidth. The best you can do is to look at the memory controller traffic triggered by IO (see the IO metric in pcm.x).
