### ISSUE TITLE
pcm-latency reports wrong value for Broadwell

### ISSUE THREAD

**Issue by soramichi** [opcm/pcm#147]
The DDR read latency reported by `pcm-latency.x` seems wrong for my Xeon E5-1603 v4 (Broadwell) machine.

```
$ sudo ./pcm-latency.x
...
DDR read Latency(ns)
6947927.16
...
```

The value of `uncore_event[DDR].skt[n].rlatency` used to calculate the DDR latency is very high and most probably wrong.

**Comment by ogbrugge** [comment]
Will check this when back in the office, could be related to the processor being single socket only but I will try to verify this next week.

**Comment by soramichi** [comment]
According to page 117 of [Intel Xeon Processor E5 and E7 v4 Product Families Uncore Performance Monitoring Reference Manual](https://www.intel.com/content/www/us/en/products/docs/processors/xeon/xeon-e5-e7-v4-uncore-performance-monitoring.html), the RPQ_OCCUPANCY event (0x80) does not exist for Broadwell, while it does exist for Xeon Scalable processors ([manual](https://software.intel.com/sites/default/files/managed/ea/25/336274-intel-xeon-processor-scalable-memory-family-uncore.pdf)).

Although it could just be an erratum of the manuals, this may explain why the value of `uncore_event[ddr].skt[i].roccupancy` is very high in my environment.

**Comment by opcm** [comment]
The event is not supported on Broadwell. We need to drop support of this metric on Broadwell.

**Comment by opcm** [comment]
fixed in master branch
