### ISSUE TITLE
What does "PMM" mean in pcm-memory.x?

### ISSUE THREAD

**Issue by yilongli** [opcm/pcm#150]
The help message says option "-pmm" means "monitor PMM memory bandwidth (instead of partial writes)". What is PMM? Persistent memory module? How is it related to partial writes? Thanks!

**Comment by nevets963** [comment]
This is specifically for monitoring the memory bandwidth of persistent memory DIMMs. For example: Optane DC Persistent Memory (https://www.intel.com/content/www/us/en/architecture-and-technology/optane-dc-persistent-memory.html)

**Comment by yilongli** [comment]
@nevets963 Thank you! It would be nice to mention that in the documentation/help message.
