### ISSUE TITLE
Measure memory bandwidth at a finer granularity?

### ISSUE THREAD

**Issue by yilongli** [opcm/pcm#151]
Hi, I am trying to use the PCM api to measure the memory bandwidth utilization from my code for a relatively short time interval (e.g., < 500 us). I used ```getMCCounter(c, 0/1, startState, endState) * 64``` to get the number of bytes read/write from/to memory. However, it appears that when the code section being measured only runs for a few hundred microseconds, the performance counter readings are often unstable/incorrect. I wonder if the reason is that pcm is trying to multiplex many metrics on top of a few pmu counters and the interval it reprograms these counters is relatively long ? If so, is there an easy way to reduce the reprogram interval? Could someone point me to the code where the reprogram happens? Thank you!

**Comment by opcm** [comment]
Hi, getMCCounter is not reprogramming counters. PCM monitors the whole system that means if in parallel some other background workload suddenly reads/write memory the measurement can be offset a lot (especially if the measurement is very short and this noise is not averaged out). This could be one of the reasons. Does it make sense to you?

**Comment by yilongli** [comment]
Maybe but I don't think this is the problem. The machine I am doing benchmark on has very little background work. Also, I switched to PAPI and was able to get very accurate measurements of the whole system bandwidth even for code that runs for <100 us.

If PCM is not doing sampling, why do I need to use `pcm->getTickCount` to get the elapsed time? Why can't I just record the start and stop time in my code? Thanks.

**Comment by opcm** [comment]
@yilongli sorry for delayed answer. Yes, you can record the start and stop time in your code.
