### ISSUE TITLE
RPM for SLES

### ISSUE THREAD

**Issue by noemmay** [opcm/pcm#160]
Hallo,
The PCM tool and the daemon is not available in SuSE enterprise Linux.  Would it be possible to provide an RPM and make it part of the distribution?
Kind regards, Norman

**Comment by opcm** [comment]
This repository is meant for distributing source code, not binaries (like RPM). If someone contributes an rpm spec file here, are there services like appveyor for Windows to build RPMs automatically?
https://ci.appveyor.com/project/opcm/pcm/build/job/3iyih4g8l8rehs2d/artifacts

That would be a preferable solution

**Comment by opcm** [comment]
RPMs from the latest PCM version are and will be available here (including SLES):  https://download.opensuse.org/repositories/home:/opcm/

**Comment by opcm** [comment]
SUSE also now maintains PCM rpms on package hub: https://packagehub.suse.com/packages/pcm/

**Comment by opcm** [comment]
I would like to close this issue because the RPMs are now available from SUSE package hub.
