### ISSUE TITLE
Using PCM on virtual machines

### ISSUE THREAD

**Issue by mehnazyunus** [opcm/pcm#167]
I attempted to run my code which used PCM energy APIs on a virtual machine, but the APIs returned the measurement as 0, while the same code provides the required measurements on the host. Is this expected behavior and is there a workaround for the same? The API used was `getConsumedJoules()`.

**Comment by opcm** [comment]
yes, this is expected because access to low-level registers that PCM uses is forbidden

**Comment by mehnazyunus** [comment]
Is there any way to work around this? I was able to get measurements for CPU cycles on the VM but not energy.

**Comment by opcm** [comment]
yes, cycles might be possible (they are collected per core), but energy counters are usually per processor package (potentially shared between VMs). I am not sure if exposing them is inline with virtualization / isolation principles.

**Comment by mehnazyunus** [comment]
Would pinning each VM to a separate core help in any way?

**Comment by opcm** [comment]
maybe if other VMs are not allowed to run on it. But it is a question for developers of virtualization hypervisors

**Comment by rodrigorras** [comment]
Anyone could check the power consumption of a container?
I did the tests last year, but doesnt seem real, I tried to log 2 running
containers and the output seems to be the same.
I was expecting to see, max-cpu Wattage/2 for 2 running containers



Em ter, 22 de out de 2019 às 07:19, opcm <notifications@github.com>
escreveu:

**Comment by opcm** [comment]
added the question to FAQ
