### ISSUE TITLE
PCM for monitoring processes

### ISSUE THREAD

**Issue by mehnazyunus** [opcm/pcm#169]
Can PCM be used for measuring energy, CPU cycles, etc for a particular process or does it measure for the system as a whole?

**Comment by opcm** [comment]
PCM supports measurement for the whole system, per processor, per physical or per logical core.

**Comment by tcinbis** [comment]
@opcm when you say that PCM supports measuring these different parts of the system, how would you specify this via the API. Unfortunately, I was not able to find a matching method in the source code documentation.

**Comment by ogbrugge** [comment]
If you use this method:
void getAllCounterStates(SystemCounterState & systemState, std::vector<SocketCounterState> & socketStates, std::vector<CoreCounterState> & coreStates);

you will get per core performance data in coreStates, uncore counter data in the socketStates and also the aggregate core counters of the cores in this socket, and aggregates for all sockets and cores plus upi/qpi information in systemState. Just create vectors and indicated and pass them into this function, the function will properly resize the vectors and fill it with counter values.

**Comment by opcm** [comment]
@mehnazyunus has your questions been answered?

**Comment by opcm** [comment]
I added a question and an answer in FAQ. Also you might try Linux perf API to monitor per user thread or per process.

**Comment by mehnazyunus** [comment]
@opcm yes they have, thank you

**Comment by opcm** [comment]
thanks for the confirmation, closing the issue
