### ISSUE TITLE
Cannot suppress output from the C API

### ISSUE THREAD

**Issue by byron-hawkins** [opcm/pcm#17]
My program links to libpcm.so and uses the C API, which does not provide a way to disable the spurious console output generated by various PCM functions. Of course it's normal for a program to write things on `stdout`, but as everyone knows, it's never acceptable for a library to do so. The best thing would be to remove all the `printf` and `cout` statements from those PCM function that are reachable via library exports.

**Comment by opcm** [comment]
thanks for reporting the issue. we are addressing it right now

**Comment by opcm** [comment]
Fix merged
