### ISSUE TITLE
Provide a make install target.

### ISSUE THREAD

**Issue by chivakker** [opcm/pcm#170]
make install should honor a user installation folder (prefix) or take a system default,

**Comment by ahkok** [comment]
The spec file demonstrates that files need to go into `/usr/bin`, but I fail to see why all the `.x` suffixes are needed. This is totally against convention.

@opcm maybe we can fix up the build system to be a bit more modern and do things like installing into the correct locations correct?

**Comment by ahkok** [comment]
https://github.com/clearlinux/distribution/issues/1390

**Comment by opcm** [comment]
@ahkok  could you please give feedback for https://github.com/opcm/pcm/pull/171

**Comment by ahkok** [comment]
https://github.com/opcm/pcm/pull/172 - very WIP though, this may take me a bit of time.

**Comment by opcm** [comment]
We are not going to lose interest in cmake but it will take more time to adopt. In meantime we got "make install" with target prefix support: https://github.com/opcm/pcm/pull/178

**Comment by opcm** [comment]
make install is now suported: https://github.com/opcm/pcm/blob/f4ef45fb99a7adfeb048e2face84450c22cf5028/Makefile#L91

**Comment by opcm** [comment]
the issue has been resolved
