### ISSUE TITLE
Could PCM work on Coffee Lake?

### ISSUE THREAD

**Issue by liujianjunhq** [opcm/pcm#177]
As tested, only some old platforms could support pcm-pcie.x, pcm-iio.x. Is there any plan or branch to support newer platforms, such as: Coffee Lake, Kaby Lake?
Jaketown, Ivytown, Haswell, Broadwell-DE Server CPU is required for this tool! Program aborted

**Comment by opcm** [comment]
does **pcm.x** work for your Coffee Lake?

**Comment by mcgrews3** [comment]
Testing on Comet Lake - 

```shell
Detected Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz "Intel(r) microarchitecture codename Kabylake" stepping 12 microcode level 0xbe        Jaketown, Ivytown, Haswell, Broadwell-DE Server CPU is required for this tool! Program aborted
```

**Comment by opcm** [comment]
iio and pcie tools are for server CPUs only. Please try pcm.x

**Comment by mcgrews3** [comment]
I am on windows trying to look at PCIe/Mem etc in support of NVMe storage (Intel Optane H10/M10) - from my reading in the Windows How To and the readme - it seems the 'x' version of things are only for linux?

**Comment by opcm** [comment]
on Windows use pcm.exe

it has IO statistics.

**Comment by opcm** [comment]
the issue has been resolved
