### ISSUE TITLE
Can't compile WinMSRDriver

### ISSUE THREAD

**Issue by letmaik** [opcm/pcm#18]
I'm trying to compile WinMSRDriver under Windows 10 within the VS 2015 developer command prompt. When it tries to run `nmake` it errors with `makefile(1) : fatal error U1052: file '\makefile.def' not found`. I downloaded [WDK 10](https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit) in the hope this is compatible (as the instructions mention the DDK).
Otherwise, I could compile the VS solution without problems, it's just the driver which is making trouble.

**Comment by opcm** [comment]
we do not support WDK10. Could you try compiling it with[ WDK 8.1](https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit)? WDK8.1 also has an option/[utility](https://msdn.microsoft.com/en-us/windows/hardware/drivers/devtest/nmake2msbuild) to convert the makefile/sources into a MSVC project.

**Comment by anurag-daware** [comment]
I have tried to compile WinMSRDriver under Windows 10 within VS 2015 with 14393 DDK.
I created new VS 2015 KMDF Project, then manually added all h and c files and compiled it. It worked fine and generated msr.sys file.
After that I generated pcm.exe but when I run pcm.exe  I get this error - SystemAccessViolation Exception

**Comment by opcm** [comment]
SystemAccessViolation issue has been resolved (fix merged)

**Comment by opcm** [comment]
@anurag-daware could you please create a pull request with your VS 2015 KMDF project? Thank you!

**Comment by anurag-daware** [comment]
sorry for the delay
Not sure how to create a pull request with my VS 2015 Win MSR Project from this repo (I use perforce extensively and newbie in git).
Here I have uploaded the same with new repo- https://github.com/anurag-daware/MSRWinDriver_VS2015
Let me know how can I help further.

**Comment by opcm** [comment]
@anurag-daware  could you try to create follow this manual (https://gist.github.com/Chaser324/ce0505fbed06b947d962) : create a fork add just MSR.inf and MSR.vcxproj into WinMSRDriver/Win7 directory and then submit a pull request?
Thank you

**Comment by opcm** [comment]
@anurag-daware  thanks for your help! I am closing this issue now

**Comment by opcm** [comment]
MSR.vcxproj is in the master branch now
