### ISSUE TITLE
Why should pcm-memory.x run with NMI watchdog disabled?

### ISSUE THREAD

**Issue by PanRui1123** [opcm/pcm#182]
I’m confused about pcm-memory's implement. Pcm-memory.x seems just read some data from uncore PMU. But PCM::PCM() will disable NMI watchdog which uses CPU's PMU to detect deadlock. There seems no relationship between those two things. So is there any influence on CPU's PMU if I read statistic from uncore PMU? Thanks!

**Comment by opcm** [comment]
it seems disabling NMI watchdog is not required. This can be improved.

**Comment by opcm** [comment]
just implemented in the master branch

**Comment by PanRui1123** [comment]
:)
