### ISSUE TITLE
pcm.x and other utilities segmentation fault please help

### ISSUE THREAD

**Issue by yaomingnew** [opcm/pcm#185]
Hi all:
I'm having an issue on Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz Kaby Lake, with Ubuntu 18.04 Linux 4.15.0-66-generic kernel
for almost every utilities in the pcm directory, I've got the issue saying seg fault or cpu unsupported.
please help, really appreciate it!

root@juge-Lenovo-YOGA-710-14IKB:/home/juge/pcm# ./pcm.x 1

 Processor Counter Monitor  ($Format:%ci ID=%h$)

IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : no
Number of physical cores: 2
Number of logical cores: 4
Number of online logical cores: 4
Threads (logical cores) per physical core: 2
Num sockets: 1
Physical cores per socket: 2
Core PMU (perfmon) version: 4
Number of core PMU generic (programmable) counters: 3
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 3
Width of fixed counters: 48 bits
Nominal core frequency: 2900000000 Hz
IBRS enabled in the kernel   : no
STIBP enabled in the kernel  : no
Package thermal spec power: 15 Watt; Package minimum power: 0 Watt; Package maximum power: 0 Watt; 
Delay: 1
Trying to use Linux perf events...
Successfully programmed on-core PMU using Linux perf
DEBUG: caught signal to interrupt (Segmentation fault).

**Comment by opcm** [comment]
thanks for reporting this issue. Are you using the latest version from the master branch? Could you please start pcm.x under gdb: gdb ./pcm.x
then type "run 1" and when it crashes "bt" to print the call stack of the crash. Please share the call stack.

**Comment by yaomingnew** [comment]
thank you for your quick response, I followed your instruction, and got the following call stack info:
======================================================================
run with gdb:
(gdb) run 1
Starting program: /home/juge/pcm/pcm.x 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

 Processor Counter Monitor  ($Format:%ci ID=%h$)


IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : no
Number of physical cores: 2
Number of logical cores: 4
Number of online logical cores: 4
Threads (logical cores) per physical core: 2
Num sockets: 1
Physical cores per socket: 2
Core PMU (perfmon) version: 4
Number of core PMU generic (programmable) counters: 3
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 3
Width of fixed counters: 48 bits
Nominal core frequency: 2900000000 Hz
IBRS enabled in the kernel   : no
STIBP enabled in the kernel  : no
Package thermal spec power: 15 Watt; Package minimum power: 0 Watt; Package maximum power: 0 Watt; 
[New Thread 0x7ffff6e85700 (LWP 19291)]
[New Thread 0x7ffff6684700 (LWP 19292)]
[New Thread 0x7ffff5e83700 (LWP 19293)]
[New Thread 0x7ffff5682700 (LWP 19294)]
[New Thread 0x7ffff4e81700 (LWP 19295)]
[New Thread 0x7ffff4680700 (LWP 19296)]
[New Thread 0x7ffff3e7f700 (LWP 19297)]
[New Thread 0x7ffff367e700 (LWP 19298)]
Delay: 1
Trying to use Linux perf events...
Successfully programmed on-core PMU using Linux perf

Thread 1 "pcm.x" received signal SIGSEGV, Segmentation fault.
0x000055555557872f in std::vector<UncorePMU, std::allocator<UncorePMU> >::operator[] (this=<optimized out>, __n=0)
    at /usr/include/c++/5/bits/stl_vector.h:780
780	      { return *(this->_M_impl._M_start + __n); }
======================================================================
call stack:
(gdb) bt
#0  0x000055555557872f in std::vector<UncorePMU, std::allocator<UncorePMU> >::operator[] (this=<optimized out>, __n=0)
    at /usr/include/c++/5/bits/stl_vector.h:780
#1  PCM::programCbo (nc_=<optimized out>, llc_lookup_tid_filter=<optimized out>, loc=<optimized out>, rem=<optimized out>, opCode=<optimized out>, 
    events=<optimized out>, this=<optimized out>) at cpucounters.cpp:6289
#2  PCM::programCbo (this=this@entry=0x5555557d4e90) at cpucounters.cpp:6374
#3  0x00005555555933f9 in PCM::program (this=0x5555557d4e90, mode_=<optimized out>, parameter_=<optimized out>) at cpucounters.cpp:2322
#4  0x000055555555ca75 in main (argc=<optimized out>, argv=<optimized out>) at pcm.cpp:1276

**Comment by opcm** [comment]
thanks a lot for this information! I pushes a fix to master branch. Please test and report if you see the sef fault or not

**Comment by yaomingnew** [comment]
thank you for your quick update, I'll test it and close the issue if everything works fine.
Thank you so much!

**Comment by opcm** [comment]
yes, please do so.

**Comment by opcm** [comment]
pls let me know if you see the issue with the latest version in the master branch. It is fixed there.

**Comment by yaomingnew** [comment]
pcm-core.x works fine with my architecture now
