### ISSUE TITLE
pcm-memory.x on Xeon E3-1220 v5?

### ISSUE THREAD

**Issue by kmarukawa** [opcm/pcm#2]
Glad to hear having new pcm repository.

Is it OK to ask something like this topic here?

We've bought machines using Intel(R) Xeon(R) CPU E3-1220 v5 and noticed pcm-memory.x is not working on this machine.  pcm.x still works through perf though.

Is it possible to solve this issue by modifying something like https://software.intel.com/en-us/forums/software-tuning-performance-optimization-platform-monitoring/topic/594458 discussion?  Thanks in advance.

**Comment by opcm** [comment]
Unfortunately it is not possible to solve it in such a way. The reason is that your processor does not have the performance monitoring unit in the memory controller that pcm-memory requires. This hardware unit is only available on Xeon E5 and E7 processors.
