### ISSUE TITLE
Power Measurement may be wrong

### ISSUE THREAD

**Issue by carlabguillen** [opcm/pcm#20]
Dear developers,

I have a Knights Landing processor and I measured power getting contradictory data.

Package minimum power: 98 Watt [..]
Watts: 43.79 [..] Consumed DRAM Joules: 1.69

Added together the total wattage is 45.48W which is less than the package minimum power 98W. Or is there a missing component whose power-data (with about 52W) is not shown ?

Thanks in advance. Below you can find the complete output.

./pcm-power.x 1

 Intel(r) Performance Counter Monitor V2.11.1 (2017-01-24 15:51:44 +0100 ID=4b0c8f7)

 Power Monitoring Utility
 Copyright (c) 2009-2016 Intel Corporation
Number of physical cores: 64
Number of logical cores: 256
Number of online logical cores: 256
Threads (logical cores) per physical core: 4
Num sockets: 1
Physical cores per socket: 64
Core PMU (perfmon) version: 3
Number of core PMU generic (programmable) counters: 2
Width of generic (programmable) counters: 40 bits
Number of core PMU fixed counters: 3
Width of fixed counters: 40 bits
Nominal core frequency: 1300000000 Hz
Package thermal spec power: 215 Watt; Package minimum power: 98 Watt; Package maximum power: 258 Watt; 
On the socket detected 2 memory controllers with total number of 6 channels. 

MC counter group: 0
PCU counter group: 0
Freq bands [0/1/2]: 1200 MHz; 2000 MHz; 4000 MHz; 
----------------------------------------------------------------------------------------------
Time elapsed: 1000 ms
Called sleep function for 1000 ms
S0CH0; DRAMClocks: 0; Rank0 CKE Off Residency: inf%; Rank0 CKE Off Average Cycles: -1; Rank0 Cycles per transition: -1
S0CH0; DRAMClocks: 0; Rank1 CKE Off Residency: inf%; Rank1 CKE Off Average Cycles: -1; Rank1 Cycles per transition: -1
S0CH1; DRAMClocks: 0; Rank0 CKE Off Residency: inf%; Rank0 CKE Off Average Cycles: -1; Rank0 Cycles per transition: -1
S0CH1; DRAMClocks: 0; Rank1 CKE Off Residency: inf%; Rank1 CKE Off Average Cycles: -1; Rank1 Cycles per transition: -1
S0CH2; DRAMClocks: 0; Rank0 CKE Off Residency: inf%; Rank0 CKE Off Average Cycles: -1; Rank0 Cycles per transition: -1
S0CH2; DRAMClocks: 0; Rank1 CKE Off Residency: inf%; Rank1 CKE Off Average Cycles: -1; Rank1 Cycles per transition: -1
S0CH3; DRAMClocks: 0; Rank0 CKE Off Residency: inf%; Rank0 CKE Off Average Cycles: -1; Rank0 Cycles per transition: -1
S0CH3; DRAMClocks: 0; Rank1 CKE Off Residency: inf%; Rank1 CKE Off Average Cycles: -1; Rank1 Cycles per transition: -1
S0CH4; DRAMClocks: 0; Rank0 CKE Off Residency: inf%; Rank0 CKE Off Average Cycles: -1; Rank0 Cycles per transition: -1
S0CH4; DRAMClocks: 0; Rank1 CKE Off Residency: inf%; Rank1 CKE Off Average Cycles: -1; Rank1 Cycles per transition: -1
S0CH5; DRAMClocks: 0; Rank0 CKE Off Residency: inf%; Rank0 CKE Off Average Cycles: -1; Rank0 Cycles per transition: -1
S0CH5; DRAMClocks: 0; Rank1 CKE Off Residency: inf%; Rank1 CKE Off Average Cycles: -1; Rank1 Cycles per transition: -1
S0; PCUClocks: 1100949255; Freq band 0/1/2 cycles: 0.00%; 0.00%; 0.00%
S0; Consumed energy units: 717516; Consumed Joules: 43.79; Watts: 43.79; Thermal headroom below TjMax: 62
S0; Consumed DRAM energy units: 110760; Consumed DRAM Joules: 1.69; DRAM Watts: 1.69
----------------------------------------------------------------------------------------------

**Comment by asemin** [comment]
Hi Carla,

Minimal Package Power (PKG_MIN_PWR) provided in MSR_PKG_POWER_INFO (0x614) bits 16-30 defines the minimal package power setting allowed for this part. Specifically for the Xeon Phi part you have the lowest power limit could be set to 98W (e.g. by writing respective parts of PACKAGE_RAPL_LIMIT_CFG). This value is reported in PCM output:
`Package thermal spec power: 215 Watt; Package minimum power: 98 Watt; Package maximum power: 258 Watt`

The measurements reported by PCM are taken RAPL Energy counters, and could be lower then minimally allowed power limit, depending on actual utilisation of the processor. If the processor is predominantly idle it may well consume 43W or less.
