### ISSUE TITLE
prometheus metrics vs json: missing metrics

### ISSUE THREAD

**Issue by aderumier** [opcm/pcm#200]
Hi,

I'm looking at prometheus metrics, it seem that some metrics are missing vs  json.

I'm looking for ""QPI/UPI Links" counters for example.

(don't have checked the full difference yet)

**Comment by ogbrugge** [comment]
The counters for UPI/QPI in Prothemeus are called:
Incoming_Data_Traffic_On_Link_<X>{socket=<Y>} 
Outgoing_Data_And_Non_Data_Traffic_On_Link_<X>{socket=<Y>}
Utilization_Incoming_Data_Traffic_On_Link_<X>{socket=<Y>}
Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_<X>{socket=<Y>}

Perhaps i should add a comment like so:
#counter UPI/QPI
or whatever the counter description format for Prometheus is

**Comment by aderumier** [comment]
Thanks for your reply !

I'm trying to reproduce influxdb dashboard (which is very great), with prometheus query, but I was lost with counter names.

I'll try to share it soon

**Comment by ogbrugge** [comment]
According to this:

[https://prometheus.io/docs/instrumenting/exposition_formats/](https://prometheus.io/docs/instrumenting/exposition_formats/)

it is not possible to use HELP or TYPE so I will insert generic comments that just start with #.

**Comment by opcm** [comment]
> Thanks for your reply !
> 
> I'm trying to reproduce influxdb dashboard (which is very great), with prometheus query, but I was lost with counter names.
> 
> I'll try to share it soon

influxdb dashboards is auto-generated. Soon there will be an generator for prometheus dashboard as well.

**Comment by opcm** [comment]
@aderumier auto-generated dashboard for prometheus backend has been added in master branch:

https://github.com/opcm/pcm/tree/master/grafana

see start-prometheus.sh

the prometheus json dashboard description for grafana is available at http://target_host:port/dashboard/prometheus

**Comment by opcm** [comment]
implemeted and finalized in https://github.com/opcm/pcm/commit/c1d684025f151c6fdeed26f6e422b7091d1907b3

**Comment by opcm** [comment]
closing since the feature has been implemented
