### ISSUE TITLE
Compiling pcm with own code example fails

### ISSUE THREAD

**Issue by tcinbis** [opcm/pcm#201]
Hello all,

I guess this is not really an issue or bug, but more a lack of missing understanding of the project (on my side). I wanted to get started but had a hard time finding any documentation or minimum examples on how to include this library in your own code. 
All I could find was #118 and some (outdated?) [blog post ](https://technicalandstuff.wordpress.com/2015/05/15/using-intels-pcm-in-linux-and-inside-c/). 

### What I did:

1. Clone this repository and checkout release 202003
2. Run `make`
3. Create a new file called `main.cpp` (see code below)
4. Compile with `g++ -std=c++11 main.cpp` in this directory

### Code 
```c
#include "cpucounters.h"

using namespace std;

int main() {
    PCM *m; // = PCM::getInstance();
    m = PCM::getInstance();
    PCM::ErrorCode returnResult = m->program();
    if (returnResult != PCM::Success) {
        std::cerr << "PCM couldn't start" << std::endl;
        std::cerr << "Error code: " << returnResult << std::endl;
        exit(1);
    }

    SystemCounterState before_sstate = getSystemCounterState();

    SystemCounterState after_sstate = getSystemCounterState();

    std::cout << "Instructions per clock:" << getIPC(before_sstate, after_sstate) << std::endl;
    std::cout << "Bytes read:" << getBytesReadFromMC(before_sstate, after_sstate) << std::endl;
    m->cleanup();
}
```
### Result/Code
```
pcm on  tags/202003 [?] via .NET 3.1.103 
➜ g++ -std=c++11 -lpthread main.cpp
/usr/bin/ld: /tmp/ccaIhFr8.o: in function `main':
main.cpp:(.text+0x9): undefined reference to `PCM::getInstance()'
collect2: error: ld returned 1 exit status
```
My final question is what am I missing to make this code compile, link and run successfully?

#### Version
Compiled with gcc version 10.1.0 on Kernel 5.6.13-arch1-1

Thanks in advance!

**Comment by ogbrugge** [comment]
You need to make sure to link to cpucounters.o which defines the PCM::getInstance statuc method and a few other objects found in the COMMON_OBJS variable in the Makefile

**Comment by tcinbis** [comment]
Thanks for your quick answer! Unfortunately even with linking against all the .o files defined in the make file I get a lot of linking errors.

The command I used:
```
g++ -std=c++11 -I . -L msr.o cpucounters.o pci.o mmio.o client_bw.o utils.o main.cpp
```

But I found a way to compile it, though I am not entirely sure whether this is the intended way of use. In the repo, there is the `pcm.so` folder with its own Makefile. When running this makefile and then compiling with the command below it seems to work.

```
g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so main.cpp
```
### Note to myself
`-rpath` tells the linker where to search for the library for example.

**Comment by ogbrugge** [comment]
Glad that the libpcm.so directory worked out for you!

For anyone reading this closed bug, for reference i meant this with COMMON_OBJS:
COMMON_OBJS = msr.o cpucounters.o pci.o mmio.o client_bw.o utils.o topology.o dashboard.o debug.o threadpool.o
(Current state as of May 19, 2020. Could be different in the future so always check)

**Comment by hamid-74** [comment]
when I run this command: `g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so main.cpp
` 
I get this error: /usr/bin/ld: cannot find -lpcm

What is the problem?

**Comment by ogbrugge** [comment]
You need to make sure your paths exist from the directory you work in. The command Tom used only works in the opcm directory. If you are somewhere else you need to fixup the path behind -L and the path behind -Wl,-rpath. This is basic gcc and ld help we're giving here so please in the future look into the man pages what the options do exactly.

**Comment by Eilowangfang** [comment]
> You need to make sure your paths exist from the directory you work in. The command Tom used only works in the opcm directory. If you are somewhere else you need to fixup the path behind -L and the path behind -Wl,-rpath. This is basic gcc and ld help we're giving here so please in the future look into the man pages what the options do exactly.

Sorry. May I know how to refer to the pcm libaray into my c++ project?

1) firstly, I tried to place the whole project under the PCM directory and compiled with 
g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so main.cpp
unfortunately, I got the same error: 
/usr/bin/ld: cannot find -lpcm


2) then, I tried  to move the project out of the PCM directory and compiled with 
g++ -L \home\**\pcm\pcm.so -lpcm -WL,-rpath=pcm.so -I\home\**\pcm\ main.cpp ...(my other c++ files).
However, the error is still:
/usr/bin/ld: cannot find -lpcm

As you suggested, I already fixup the path behind -L.

Can I know how to solve this, 
in a g++ compiling command or  CMakelist code. Both are OK.

Thanks a lot.

**Comment by Eilowangfang** [comment]
> You need to make sure your paths exist from the directory you work in. The command Tom used only works in the opcm directory. If you are somewhere else you need to fixup the path behind -L and the path behind -Wl,-rpath. This is basic gcc and ld help we're giving here so please in the future look into the man pages what the options do exactly.

By the way, I just repeat the example of user "tcinbis"，
place the example c++ under PCM directory and compiled with:
g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so main.cpp 

the error is still there:
/usr/bin/ld: cannot find -lpcm
collect2: error: ld returned 1 exit status

**Comment by ogbrugge** [comment]
I see you used \ instead of /, can you fix that up and try agin?

**Comment by Eilowangfang** [comment]
> I see you used \ instead of /, can you fix that up and try agin?
> […](#)
> Sent from my iPhone
> On 30. May 2020, at 04:58, Eilowangfang ***@***.***> wrote: ﻿ You need to make sure your paths exist from the directory you work in. The command Tom used only works in the opcm directory. If you are somewhere else you need to fixup the path behind -L and the path behind -Wl,-rpath. This is basic gcc and ld help we're giving here so please in the future look into the man pages what the options do exactly. By the way, I just repeat the example of user "tcinbis"， place the example c++ under PCM directory and compiled with: g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so main.cpp the error is still there: /usr/bin/ld: cannot find -lpcm collect2: error: ld returned 1 exit status — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

sorry for mistyping.
Sure, what I tried is "/ ": for example, the path /home/../pcm/pcm.so in linux.
The error is still same. 

I was wondering if "pcm" is correct, and then I tried "-llibpcm", but similar error:
/usr/bin/ld: cannot find -llibpcm

**Comment by ogbrugge** [comment]
You do need to go into the pcm.so directory and build it if you have not done so, the library is then called libpcm.so as you can see in the makefile.

Then you need to use relative or absolute paths for -L and use -lpcm, the linker will replace that with libpcm.so.

Von meinem iPad gesendet

**Comment by Eilowangfang** [comment]
> You do need to go into the pcm.so directory and build it if you have not done so, the library is then called libpcm.so as you can see in the makefile. Then you need to use relative or absolute paths for -L and use -lpcm, the linker will replace that with libpcm.so. Von meinem iPad gesendet
> […](#)
> Am 30.05.2020 um 10:11 schrieb Eilowangfang ***@***.***>: ﻿ I see you used \ instead of /, can you fix that up and try agin? … Sent from my iPhone On 30. May 2020, at 04:58, Eilowangfang @.***> wrote: ﻿ You need to make sure your paths exist from the directory you work in. The command Tom used only works in the opcm directory. If you are somewhere else you need to fixup the path behind -L and the path behind -Wl,-rpath. This is basic gcc and ld help we're giving here so please in the future look into the man pages what the options do exactly. By the way, I just repeat the example of user "tcinbis"， place the example c++ under PCM directory and compiled with: g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so main.cpp the error is still there: /usr/bin/ld: cannot find -lpcm collect2: error: ld returned 1 exit status — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. sorry for mistyping. Sure, what I tried is "/ ": for example, the path /home/../pcm/pcm.so in linux. The error is still same. I was wondering if "pcm" is correct, and then I tried "-llibpcm", but similar error: /usr/bin/ld: cannot find -llibpcm — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks. I moved a step forward with your help. 
Now I created libpcm.so.
Then I place my test.cpp on the PCM directory, then compiled with:
g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so test.cpp 

Well, there is a new error that I have no idea what it is:
pcm.so/libpcm.so: undefined reference to `Socket::Socket(PCM*, int, int)'.

This is ?

**Comment by ogbrugge** [comment]
I’ll need to check this on Monday, not sure what problem this points at. Perhaps there is a missing commit to GitHub.

**Comment by Eilowangfang** [comment]
> I’ll need to check this on Monday, not sure what problem this points at. Perhaps there is a missing commit to GitHub.
> […](#)
> Sent from my iPhone
> On 30. May 2020, at 13:12, Eilowangfang ***@***.***> wrote: ﻿ You do need to go into the pcm.so directory and build it if you have not done so, the library is then called libpcm.so as you can see in the makefile. Then you need to use relative or absolute paths for -L and use -lpcm, the linker will replace that with libpcm.so. Von meinem iPad gesendet … Am 30.05.2020 um 10:11 schrieb Eilowangfang @.>: ﻿ I see you used \ instead of /, can you fix that up and try agin? … Sent from my iPhone On 30. May 2020, at 04:58, Eilowangfang @.> wrote: ﻿ You need to make sure your paths exist from the directory you work in. The command Tom used only works in the opcm directory. If you are somewhere else you need to fixup the path behind -L and the path behind -Wl,-rpath. This is basic gcc and ld help we're giving here so please in the future look into the man pages what the options do exactly. By the way, I just repeat the example of user "tcinbis"， place the example c++ under PCM directory and compiled with: g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so main.cpp the error is still there: /usr/bin/ld: cannot find -lpcm collect2: error: ld returned 1 exit status — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. sorry for mistyping. Sure, what I tried is "/ ": for example, the path /home/../pcm/pcm.so in linux. The error is still same. I was wondering if "pcm" is correct, and then I tried "-llibpcm", but similar error: /usr/bin/ld: cannot find -llibpcm — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Thanks. I moved a step forward with your help. Now I created libpcm.so. Then I place my test.cpp on the PCM directory, then compiled with: g++ -L pcm.so -lpcm -Wl,-rpath=pcm.so test.cpp Well, there is a new error that I have no idea what it is: pcm.so/libpcm.so: undefined reference to `Socket::Socket(PCM*, int, int)'. This is ? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes. Thank you. Looking forward your reply.

**Comment by ogbrugge** [comment]
I think this bit is missing:

diff --git a/pcm.so/Makefile b/pcm.so/Makefile
index c3e2976..3307e09 100644
--- a/pcm.so/Makefile
+++ b/pcm.so/Makefile
@@ -6,7 +6,7 @@ OPT= -g -O3
 CXXFLAGS+= -Wall -fPIC $(OPT) -std=c++11 -DPCM_SILENT
 vpath %.cpp ..

-libpcm.so: msr.o cpucounters.o pci.o mmio.o client_bw.o utils.o pcm-core.o
+libpcm.so: msr.o cpucounters.o pci.o mmio.o client_bw.o utils.o pcm-core.o
topology.o debug.o threadpool.o
        $(CXX) $(CXXFLAGS) -shared $^ -lpthread -o $@

 c_example.x: c_example.o

Can you add the 3 objects to the Makefile in pcm.so and try again?

**Comment by ogbrugge** [comment]
I have not heard anything back, can you please acknowledge whether this change fixes the problem for you?

**Comment by Eilowangfang** [comment]
> I have not heard anything back, can you please acknowledge whether this change fixes the problem for you?

Yes. It works now. Thanks a lot.

**Comment by ogbrugge** [comment]
Thank you!

**Comment by yushangdi** [comment]
Hi, I read the posts above and try to compile the code, but the command does not work for me. Here's what I did:

cloned the master branch with commit [5803928](https://github.com/opcm/pcm/commit/58039287e0ee63edcaa60bdbf837d536e4e417da)

run 'git clone https://github.com/simdjson/simdjson.git' in src directory to get simdjson library

mkdir build in pcm/
cd build
cmake ..
cmake --build .


now I created a file that is the same as the original post in pcm/../folder/:

`
#include "cpucounters.h"

using namespace std;

int main() {
    PCM *m; // = PCM::getInstance();
    m = PCM::getInstance();
    PCM::ErrorCode returnResult = m->program();
    if (returnResult != PCM::Success) {
        std::cerr << "PCM couldn't start" << std::endl;
        std::cerr << "Error code: " << returnResult << std::endl;
        exit(1);
    }

    SystemCounterState before_sstate = getSystemCounterState();

    SystemCounterState after_sstate = getSystemCounterState();

    std::cout << "Instructions per clock:" << getIPC(before_sstate, after_sstate) << std::endl;
    std::cout << "Bytes read:" << getBytesReadFromMC(before_sstate, after_sstate) << std::endl;
    m->cleanup();
}
`

in folder/ I run
 g++ -L../pcm/build/lib/pcm.so -lpcm -Wl,-rpath=../pcm/build/lib/pcm.so main.cpp 

This gives me error:

main.cpp:1:10: fatal error: cpucounters.h: No such file or directory
 #include "cpucounters.h"


I also tried to put the c_example.c file from pcm/examples in folder, and run

g++ -L../pcm/build/lib/libpcm.so -lpcm -Wl,-rpath=../pcm/build/lib/libpcm.so c_example.c 

This gives me error:

/usr/bin/ld: cannot find -lpcm


I'm wondering what I did wrong? Thank you!

**Comment by ogbrugge** [comment]
Normally you have to add a flag to g++ to tell it where the header files are and where the library is if you do not build in the directory where these files are:

-I/path/to/cpucounters.h -L/path/to/libpcm.so

**Comment by yushangdi** [comment]
Thanks for the quick reply! I added the -I flag and tried the following:

 g++ -I../pcm/src/ -L../pcm/build/lib/ -lpcm -Wl,-rpath=../pcm/build/lib/ -DPCM_DYNAMIC_LIB -pthread main.cpp -ldl

but I still got errors:

```
main.cpp: In function ‘int main()’:
main.cpp:6:5: error: ‘PCM’ was not declared in this scope
     PCM *m; // = PCM::getInstance();
     ^~~
main.cpp:6:5: note: suggested alternative:
In file included from main.cpp:1:0:
../pcm/src/cpucounters.h:553:15: note:   ‘pcm::PCM’
 class PCM_API PCM
               ^~~
main.cpp:6:10: error: ‘m’ was not declared in this scope
     PCM *m; // = PCM::getInstance();
          ^
main.cpp:6:10: note: suggested alternative: ‘tm’
     PCM *m; // = PCM::getInstance();
          ^

......
```
