### ISSUE TITLE
namespaces

### ISSUE THREAD

**Issue by piotrchmiel** [opcm/pcm#208]
Is there any particular reason that namespaces are not used in the project ? It seems that there is no C API and code is written in pure C++. Using namespace would allow the user to avoid a potential conflicts with the names and doing workarounds for that problem like writing wrappers for the lib and hide included headers in one translation unit.

**Comment by opcm** [comment]
yes, this is a valid request. Please let us know if you already have experienced such conflict.

**Comment by piotrchmiel** [comment]
Yes, I experienced it when I wanted to use it in project where I'm contributor: https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/README.md. Unfortunately, now I don't remember what exact names conflicted with ours, but there was not one but several issues with naming.
