### ISSUE TITLE
pcm.so makefile

### ISSUE THREAD

**Issue by piotrchmiel** [opcm/pcm#209]
Is it possible to fix pcm.so Makefile ? It seems that there is lack some COMMON_OBJS from main Makefile.

**Comment by ogbrugge** [comment]
See issue #201

**Comment by ogbrugge** [comment]
Sorry that was a bit blunt. Thank you for reporting, the solution could be in issue 201, please apply the 3 objects that are missing as indicated in the diff and let me know if that fixes the problem for you.

**Comment by piotrchmiel** [comment]
Unfortunately is not that easy, I'm using OSX. As I can see in main Makefile there is decision tree about linking libraries based on os. On OSX I need to link also provided driver. When I fixed that and libpcm.so landed in my directory attached example is still not working:

Undefined symbols for architecture x86_64:
  "_sched_getcpu", referenced from:
      _main in c_example.o
ld: symbol(s) not found for architecture x86_64

**Comment by ogbrugge** [comment]
sched_getcpu is normally a system library function, does OSX/FreeBSD have something similar?

**Comment by opcm** [comment]
I moved the lib and the example to the main Makefile to keep the common objs in sync: https://github.com/opcm/pcm/commit/0d75a107bef6f5ddb1f9c9a3f4fe9d51163b72af

Still for non Linux OSes the getcpu function needs to be implemented through cpuid instruction.
