### ISSUE TITLE
SystemAccessViolation Exception while running pcm.exe

### ISSUE THREAD

**Issue by anurag-daware** [opcm/pcm#21]
I have tried to compile WinMSRDriver under Windows 10 within VS 2015 with 14393 DDK.
I created new VS 2015 KMDF Project, then manually added all h and c files and compiled it. It worked fine and generated msr.sys file.
After that I generated pcm.exe but when I run pcm.exe I get this error - SystemAccessViolation Exception
Platform - win1064 RS1 14393 + Kabylake
log as below

D:\PCM>pcm.exe
DEBUG: Setting Ctrl+C done.

 Processor Counter Monitor  (2017-03-24 23:15:23 +0100 ID=ea6ef86)

Starting MSR service failed with error 1275 This driver has been blocked from loading
Trying to load winring0.dll/winring0.sys driver...

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at mainCRTStartup()
DEBUG: Unhandled Exception event

**Comment by opcm** [comment]
thanks for reporting this. The original issue is that **"This driver has been blocked from loading"**. You need to sign your driver to avoid the blocking. Of course the following access violation exception will be fixed soon (it should not happen even if the driver is not usable).
You can follow test signing instructions [here](https://software.intel.com/en-us/forums/software-tuning-performance-optimization-platform-monitoring/topic/371243#comment-1728744) or use a third-party WinRing0 driver.

**Comment by anurag-daware** [comment]
Ok But I have built my driver using VS2015, it took care of signing then what went wrong? any ideas?

**Comment by opcm** [comment]
Did you restart your system in TESTSIGNING mode? Could you please create a pull request with your VS 2015 KMDF Project file?

**Comment by opcm** [comment]
Fix merged

**Comment by opcm** [comment]
The original issue (SystemAccessViolation) has been resolved. I am going to close this issue.
