### ISSUE TITLE
getMaxCustomCoreEvent() different output on same CPU

### ISSUE THREAD

**Issue by VenturaDelMonte** [opcm/pcm#216]
Hi all, i am using PCM on Linux server with a `Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz Intel(r) microarchitecture codename Skylake-SP stepping 4`. When I execute my application as `sudo`,  calling `getMaxCustomCoreEvent()` on the PCM instance returns 3. As a result, I can program only 3 custom counters. However, my understanding of the Skylake arch. is that I should be able to program up to 4 counters.  The error I get is: `Trying to program 4 general purpose counters with only 3 available`.
Please, note that running the app without `sudo` results in 4 general purpose counters being detected. Of course, the app crashes as `/dev/cpu/*/msr` are not readable without sudo.

My question for you is whether this is expected and what solution would be suitable to resolve the problem at hand. I also tried to set the `setuid` as well as `cap_sys_admin` but it did not work. Do you have any suggestion?

**Comment by opcm** [comment]
without MSR access the number of available counters can't be determined correctly. Need to change coding to prevent incorrect reporting when the MSR access is not available.

**Comment by VenturaDelMonte** [comment]
Thanks for your reply. Does this mean that `PCM::readCoreCounterConfig` is reading the `cpuid` info wrongly, i.e., extracting `core_gen_counter_num_max` incorrectly? Or have i misunderstood your answer?

**Comment by opcm** [comment]
the information from cpuid needs to be overruled by MSR value on your CPU

**Comment by VenturaDelMonte** [comment]
I think the value is read correctly but then it gets decremented here:

```
if (isForceRTMAbortModeAvailable() && MSR.size()) {
            uint64 TSXForceAbort = 0;
            if (MSR[0]->read(MSR_TSX_FORCE_ABORT, &TSXForceAbort) == sizeof(uint64)) {
                TSXForceAbort &= 1;
                /*
                    TSXForceAbort is 0 (default mode) => the number of useful gen counters is 3
                    TSXForceAbort is 1                => the number of gen counters is unchanged
                */
                if (TSXForceAbort == 0) {
                    core_gen_counter_num_max = 3; // here
                    fprintf(stderr, "TSXForceAbort reduced counters\n");
                }
            } else {
                std::cerr << "PCM Error: reading MSR_TSX_FORCE_ABORT failed. \n";
            }
        }
```

If i may ask, what is the rationale behind this check? Would it be safe to skip it the user called `disableForceRTMAbortMode` ?

**Comment by opcm** [comment]
The details are described here: https://cdrdv2.intel.com/v1/dl/getContent/604224

You need to call PCM::enableForceRTMAbortMode() to get the forth counter back but the call requires again access to MSR for the correct functioning

**Comment by VenturaDelMonte** [comment]
Thanks for your reply and explanation. It's clear now! I somehow missed this detail. 
I confirm i could get the 4th counter back (running as sudo) after calling `PCM::enableForceRTMAbortMode`.

**Comment by VenturaDelMonte** [comment]
I have a followup question - if i may. Should `PCM::readCoreCounterConfig` detect 8 generic counters, if HT is disabled? 
I disabled HT via `echo off | sudo tee  /sys/devices/system/cpu/smt/control` but `cpuid` still gives me 4 counters. Am I missing something or i should get 8 of them?  

P.s.: I know that disabling HT in the BIOS should probably be the right way to disable HT, however i cant do that.

**Comment by opcm** [comment]
CPU cpuid instruction does not know about /sys/devices/system/cpu/smt/control (it just does not schedule anything on the other HT thread but HT is still on). You need to disable HT in the BIOS to have more generic counters.

**Comment by VenturaDelMonte** [comment]
@opcm thanks for your very quick reply. I know that the following might sound as a bad idea but would bypassing the cpuid check and program 8 counters anyway be safe (by slightly modifying the pcm code)?  Or would this be prevented by the BIOS settings?

**Comment by opcm** [comment]
the programming will not work when driver will try to write the (4..8th) PMU register that do not exist in "SMT on" mode.

**Comment by opcm** [comment]
the other 4 counters will return zeros because nothing is executed on the sibling logical core

**Comment by VenturaDelMonte** [comment]
yes, i understand. It makes sense. Thanks very much for your explanation and prompt replies.
