### ISSUE TITLE
using pcm.x works but inside my code throws PCMBusy

### ISSUE THREAD

**Issue by kai-chi** [opcm/pcm#218]
hi,

I'm trying to start using PCM on `Intel Core i7-8565U` but I'm running into a problem while using it inside my code. The tool works fine when run separately from the CLI. What I did:
1. `make` PCM on my machine
2. `sudo ./pcm.x` works fine and I'm getting readings in real time
3. I wrote a simple PCM example to use the counters
   
        #include "/home/kaichi/repo/pcm/cpucounters.h"
        using namespace std;

        main(){

          PCM *m = PCM::getInstance();
          //m->resetPMU();
          m->program(PCM::DEFAULT_EVENTS, NULL);
          PCM::ErrorCode ret = m->program();
          if (ret != PCM::Success) {
            cout << "Failed to load PCM" << endl;
            cout << "Error code: " << ret << endl;
            m->cleanup();
            return -1;
          }
  
          SystemCounterState before = getSystemCounterState();
  
          cout<<"put my code here"<<endl;
  
          SystemCounterState after = getSystemCounterState();
          cout << "Instructions per clock:" << getIPC(before,after)<<endl;
          cout <<"L3 Cache Misses"<< getL3CacheMisses(before,after)<<endl;
          cout << "L2 Cache Misses"<<getL2CacheMisses(before,after)<<endl;
          cout << "L3 cache hit ratio:" << getL3CacheHitRatio(before,after)<<endl;
          cout << "L2 cache hit ratio"<<getL2CacheHitRatio(before, after)<<endl;
          m->cleanup();
        }
4. compiled the code with `g++ -L/home/kaichi/repo/pcm/ -lpcm -Wl,-rpath=/home/kaichi/repo/pcm/libpcm.so main.cpp -o main`
5. when running (as sudo) `./main` I'm getting:

        Error while reading perf data. Result is 0
        Check if you run other competing Linux perf clients.
        Instructions per clock:-1
        L3 Cache Misses0
        L2 Cache Misses0
        L3 cache hit ratio:-nan
        L2 cache hit ratio-nan
        Cleaning up
         Zeroed uncore PMU registers
6. I went to PCM's Makefile, commented out the line with `CXXFLAGS += -DPCM_USE_PERF` and `make` again
7. I recompiled my app and now I'm getting:

        WARNING: Custom counter 0 is in use. MSR_PERF_GLOBAL_INUSE on core 0: 0x70000000f
        WARNING: Custom counter 1 is in use. MSR_PERF_GLOBAL_INUSE on core 0: 0x70000000f
        WARNING: Custom counter 2 is in use. MSR_PERF_GLOBAL_INUSE on core 0: 0x70000000f
        WARNING: Custom counter 3 is in use. MSR_PERF_GLOBAL_INUSE on core 0: 0x70000000f
        WARNING: Core 0 IA32_PERFEVTSEL0_ADDR is not zeroed 4399313
        Failed to load PCM
        Error code: 2
        Cleaning up
         Zeroed PMU registers
         Zeroed uncore PMU registers
8. Error code 2 is PMUBusy so I rebooted the machine and it's still behaving the same
9. I tried adding `m->resetPMU();` in my code but no effects

So, I am able to run `./pcm.x` and get nice results but my app is not working. Am I missing something? 
I would be grateful for any help.

PS. I tried to solve the problem with these:
https://community.intel.com/t5/Software-Tuning-Performance/Can-t-use-PCM/td-p/802189
https://github.com/intelsdi-x/snap-plugin-collector-pcm/issues/38

**Comment by kai-chi** [comment]
I just tried to reset the PMU later. That is, I swapped two lines from my code from the first comment:

    m->program(PCM::DEFAULT_EVENTS, NULL);
    m->resetPMU();

It actually works but is an ugly (and potentially harmful) workaround. Is there a way to avoid resetting it every time?

**Comment by ogbrugge** [comment]
PCM * pcmInstance = PCM::getInstance();
        do {
            status = pcmInstance->program();
            switch ( status ) {
                case PCM::PMUBusy:
                {
                    if ( forcedProgramming == false ) {
                        std::cout << "Warning: PMU appears to be busy, do you want to reset it? (y/n)\n";
                        char answer;
                        std::cin >> answer;
                        if ( answer == 'y' || answer == 'Y' )
                            pcmInstance->resetPMU();
                        else
                            exit(0);
                    } else {
                        pcmInstance->resetPMU();
                    }
                    break;
                }
                case PCM::Success:
                    break;
                case PCM::MSRAccessDenied:
                case PCM::UnknownError:
                default:
                    exit(1);
            }
        } while( status != PCM::Success );

I use this code in pcm-sensor-server.cpp. Yes if the PMU is busy for some reason, perf is running or vtune or so then pcm will not program the PMU unless you tell it to by doing a reset first. Perhaps the reason is a bad BIOS that does not properly clear the PMU registers.

**Comment by kai-chi** [comment]
@ogbrugge, thanks a lot for a quick reply. I don't think anything else was running on the machine so would put my guess on the BIOS. anyways, user confirmation is a good solution for my case.
