### ISSUE TITLE
Dose pcm support Redhat enterprise 6.3 on  Xeon E5-2690?

### ISSUE THREAD

**Issue by mrhewenjun** [opcm/pcm#219]
report that there is no msr  module found.

 Processor Counter Monitor  (2020-03-09 16:26:23 +0100 ID=4e3c199)

IBRS and IBPB supported  : no
STIBP supported          : no
Spec arch caps supported : no
Number of physical cores: 16
Number of logical cores: 32
Number of online logical cores: 32
Threads (logical cores) per physical core: 2
Num sockets: 2
Physical cores per socket: 8
Core PMU (perfmon) version: 3
Number of core PMU generic (programmable) counters: 4
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 3
Width of fixed counters: 48 bits
Nominal core frequency: 2900000000 Hz
Package thermal spec power: 135 Watt; Package minimum power: 51 Watt; Package maximum power: 215 Watt; 
ERROR: QPI LL monitoring device (0:3f:8:2) is missing. The QPI statistics will be incomplete or missing.
ERROR: QPI LL monitoring device (0:3f:9:2) is missing. The QPI statistics will be incomplete or missing.
Socket 0: 1 memory controllers detected with total number of 4 channels. 0 QPI ports detected. 0 M2M (mesh to memory) blocks detected. 0 Home Agents detected.
ERROR: QPI LL monitoring device (0:7f:8:2) is missing. The QPI statistics will be incomplete or missing.
ERROR: QPI LL monitoring device (0:7f:9:2) is missing. The QPI statistics will be incomplete or missing.
Socket 1: 1 memory controllers detected with total number of 4 channels. 0 QPI ports detected. 0 M2M (mesh to memory) blocks detected. 0 Home Agents detected.
Disabling NMI watchdog since it consumes one hw-PMU counter.
Trying to use Linux perf events...
Using PCM on your system might have a performance impact as per http://software.intel.com/en-us/articles/performance-impact-when-sampling-certain-llc-events-on-snb-ep-with-vtune
You can avoid the performance impact by using the option --noJKTWA, however the cache metrics might be wrong then.
Linux Perf: Error on programming CPU_CLK_UNHALTED_REF: Invalid argument
Access to Processor Counter Monitor has denied (Unknown error).
Cleaning up
 Zeroed uncore PMU registers
 Re-enabling NMI watchdog.

**Comment by ogbrugge** [comment]
The QPI monitoring device is hidden, this could be a BIOS issue. Can you check in the BIOS is there is asetting to make the QPI device visible? If not you may have to find a BIOS from your vendor that allows this.

**Comment by opcm** [comment]
the QPI perfmon devices are hidden as @ogbrugge indicated. To get other metrics work please use PCM_NO_PERF=1 environment variable to work-around the old Linux perf  kernel issue: https://github.com/opcm/pcm/blob/master/ENVVAR_README.md

**Comment by opcm** [comment]
Did PCM_NO_PERF=1 help?
