### ISSUE TITLE
Does PCM support Kabylake CPUs (e.g. Intel i5-7300HQ) ?

### ISSUE THREAD

**Issue by anurag-daware** [opcm/pcm#22]
D:\CEC\PCM>pcm.exe
DEBUG: Setting Ctrl+C done.

 Processor Counter Monitor  (2017-03-24 23:15:23 +0100 ID=ea6ef86)

Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Broadwell-EP/EX, Broadwell-DE, Knights Landing, Skylake). CPU model number: 158 Brand: **"Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz"**
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).

**Comment by opcm** [comment]
thanks for reporting this issue. Kabylake has the same performance events as Skylake. As a temp workaround please change the Skylake id in cpucounter.h to 158.
SKL = 94, -> SKL = 158,

**Comment by anurag-daware** [comment]
Thanks for the reply.
I have 1 question about pcm-msr utility, not sure where should I ask this so asking here - 
Its description says - MSR read/write utility
But how should I provide MSR address and read it? e.g. I want to read 3F8h
In usage - 
Usage pcm-msr.exe [-w value] [-c core] [-d] msr

  Reads specified msr (model specific register)
   -w value : write the value before reading
   -c core  : perform msr read/write on specified core (default is 0)
   -d       : output all numbers in dec (default is hex)
Where is the read option with input to give MSR address?
Thanks

**Comment by opcm** [comment]
pcm-msr.exe 0x3F8

**Comment by opcm** [comment]
Fix merged
