### ISSUE TITLE
 pcm-iio.x Isn't working on Freebsd

### ISSUE THREAD

**Issue by darkfiberiru** [opcm/pcm#223]
sudo pcm-iio.x isn't working. Sig aborting?

Tried on head with latest intel-pcm-devl freebsdport

 
From GDB
 
Thread 1 received signal SIGABRT, Aborted.
0x00000008005e630a in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x00000008005e630a in thr_kill () from /lib/libc.so.7
#1  0x00000008005e5cb4 in raise () from /lib/libc.so.7
#2  0x000000080055bbe9 in abort () from /lib/libc.so.7
#3  0x00000008003cf919 in ?? () from /lib/libcxxrt.so.1
#4  0x0000000000224eb3 in ?? ()
#5  0x0000000000226fc9 in ?? ()
#6  0x000000000021f660 in ?? ()
#7  0x000000000021f560 in ?? ()
#8  0x0000000000000000 in ?? ()
(gdb) q
A debugging session is active.

**Comment by opcm** [comment]
was there any output before the crash? could you recompile with -O0 -ggdb options disabling -O3 optimizations such that hopefully function names are visible in the bt?

**Comment by jimharris** [comment]
Hi @darkfiberiru,

Could you also try building from latest GitHub master and see if the issue reproduces?

Does this only happen with pcm-iio, or other PCM utilities as well?

Thanks,

Jim

**Comment by darkfiberiru** [comment]
When I have a chance(Sorry very busy at moment) I will compile with latest This issue is only with pcm-iio as far as I've seen. Mo coworkers and I at iXsystems are heavily using other intel-pcm tools.

Intel-pcm-devel port is at commit b5f69fc.

**Comment by mjguzik** [comment]
First a minor remark that FREEBSD_README.txt fails to mention that *g*make is required, instead it directly refers to Linux.

Second, the intel-pcm port was recently updated to 202007 snapshot, while intel-pcm-devel is still lagging behind it.

The 202007 works port for me while the older one crashes, iow the update should take care of it.

**Comment by opcm** [comment]
@mjguzik I am glad to hear the issue has been resolved in the latest snapshot. I am not sure who is the owner of intel-pcm-devel port...

**Comment by mjguzik** [comment]
I can prod the owner and get the port sorted out. I don't know your policy here, I suspect this can be closed in few days if the reporter does not respond.

**Comment by opcm** [comment]
@mjguzik thanks a lot, that sounds good
