### ISSUE TITLE
PCM-IIO for non-Xeon Intel CPUs?

### ISSUE THREAD

**Issue by ted-xie** [opcm/pcm#227]
Hi PCM team,

From a quick glance of your documentation, it looks like Intel Core-series processors should be supported.

> [...] monitor performance and energy metrics of Intel® Core™, Xeon®, Atom™ and Xeon Phi™ processors

However, it looks like PCM-IIO is not supported for my Core i5. The banner of the console output seems to indicate only Skylake-SP is supported.

```
 Processor Counter Monitor  ($Format:%ci ID=%h$)                                                                      
                                                                                                                      
 This utility measures Skylake-SP IIO information     
[...]
Skylake Server CPU is required for this tool! Program aborted
Cleaning up
 Zeroed uncore PMU registers
```

Is there a way I can monitor my PCIe link bandwidth using one of the PCM utilities? FYI I am using Ubuntu 16.04 on Linux kernel 4.15.0.

Thanks!

-TX

**Comment by opcm** [comment]
the closest I can think of is the "IO" metric in pcm.x

**Comment by opcm** [comment]
added the question to FAQ
