### ISSUE TITLE
Inconsistent format for L2MISS and L3MISS counters in csv and normal outputs

### ISSUE THREAD

**Issue by ChanderG** [opcm/pcm#228]
The default output shows these counters as raw numbers (eg, 52K).
However the csv output format has the same numbers rendered as floats (eg, 0.03) without any additional rate calculations. 

Not clear if this is the expected behaviour, but looks like a bug.

**Comment by opcm** [comment]
this is expected behavior:
https://software.intel.com/content/www/us/en/develop/blogs/intel-pcm-column-names-decoder-ring.html

the unit_format is for human readable format only.

**Comment by opcm** [comment]
unit_format is not appropriate for machine readable output (csv). Suffixes added there are harder to parse with scripts or programs (like Excel) which consume csv.

**Comment by ChanderG** [comment]
Ah! Thanks for that. 
Would be very useful to point to that page somewhere in the command's help section or the repo readme.

**Comment by opcm** [comment]
@ChanderG , good idea. Would you be able to submit a PR adding a reference to https://software.intel.com/content/www/us/en/develop/blogs/intel-pcm-column-names-decoder-ring.html in pcm --help ?

**Comment by ChanderG** [comment]
Sure. Will do.
