### ISSUE TITLE
Regarding output of pcm.exe

### ISSUE THREAD

**Issue by anurag-daware** [opcm/pcm#23]
Hi
I am running pcm.exe and it dumps output to console window, I have some doubts regarding the output- 
".....
 C1 core residency: 1.27 %; C3 core residency: 0.00 %; C6 core residency: 0.00 %; C7 core residency: 95.40 %;
 C2 package residency: 22.54 %; C3 package residency: 0.06 %; C6 package residency: 0.01 %; C7 package residency: 62.43 %; C8 package residency: 0.00 %; C9 package residency: 0.00 %; C10 package residency: 0.00 %;
"
1. Looking the quoted output from pcm.exe, I can understand that package residencies are per core per what about core residency, when it dumps core residency, where does it specific for which core this residency is dumped for?
2. Is there any command line option which can only dump C state residency unless I want to change the code and build new binary to dump only C state.

Thank you

**Comment by opcm** [comment]
1. this line sums up core residencies for all cores = sum(cycles in core C_x state on core y) / sum (TSC cycles on core y) for all cores y
2. no. but you can use grep command (from cygwin on Windows) to filter only information you want

**Comment by anurag-daware** [comment]
Looks good let me get back if any more question closing this for now!
