### ISSUE TITLE
Negative Values for IPC in Output - CentOS 7.4

### ISSUE THREAD

**Issue by ajithAI** [opcm/pcm#232]
OS : CentOS 7.4 

Output of the PCM is having Negative Values for IPC & AFREQ

Command : sudo ./pcm.x 

![PCM_OUTPUT](https://user-images.githubusercontent.com/39941665/94108018-2cc86b80-fe5c-11ea-8d78-970677bbc741.jpg)

**Comment by opcm** [comment]
this is likely to be an issue with Linux perf driver. As a workaround, could you try to run

`PCM_NO_PERF=1 ./pcm.x -r`

doc: https://github.com/opcm/pcm/blob/master/ENVVAR_README.md

Let me know if it works for you.

**Comment by ajithAI** [comment]
Still Negative Values even after trying -> PCM_NO_PERF=1 ./pcm.x -r

**Comment by opcm** [comment]
are there any other PCM instances or other perf tools running in parallel? Rebooting might help. When you use the last command line did you see any additional errors or warnings? Could you share the complete output from the beginning?

**Comment by ajithAI** [comment]
There are no other PCM Processes / PERF tools Running 
Even After Reboot, still facing the issue. 

**Command Log Details :** 

![image](https://user-images.githubusercontent.com/39941665/94130738-ac653300-fe7a-11ea-88c4-79e6dbb8e16c.png)


![image](https://user-images.githubusercontent.com/39941665/94130028-bdfa0b00-fe79-11ea-8235-4524e71623c9.png)

 **Output Log :** 

![image](https://user-images.githubusercontent.com/39941665/94130202-fac60200-fe79-11ea-96a2-cc5bd4b1b99a.png)

![image](https://user-images.githubusercontent.com/39941665/94130261-0dd8d200-fe7a-11ea-9791-03188b7f3846.png)

**Comment by opcm** [comment]
in the first screenshot I see that PCM is "using Linux perf". Could you please disable the perf usage (the last command I sent) and send the output?

**Comment by opcm** [comment]
I see the issue now. You set this variable before sudo. It has no effect on PCM. Please run as root and set this variable inside root shell

**Comment by ajithAI** [comment]
Hi, 

Thanks. The issue resolved when I entered as ```root``` 
And also, this worked :  ( without entering as root, just using sudo )  
- Keep ```PCM_NO_PERF=1 ./pcm.x```  in a file, say ```run.sh```

```bash 
sudo ./run.sh
```  
Thanks @opcm , for your support & quick resolve. Really appreciate your help.  
Ajith.
