### ISSUE TITLE
Building PCM on Windows Server 2016 VM (Hyper-V)

### ISSUE THREAD

**Issue by antonionehme** [opcm/pcm#233]
Hi,

I am trying to build PCM by following the instructions on Windows_HOWTO.
When I try to build MSR, I get the error below
![image](https://user-images.githubusercontent.com/11300985/94690244-c776ed80-0327-11eb-9c3f-c11f2538b60f.png)

I have Windows 10 SDK installed as part on my virtual studio (see below)
![image](https://user-images.githubusercontent.com/11300985/94690355-ec6b6080-0327-11eb-97d9-3823a29b9660.png)

Any advice on how to fix the error or tips on how to compile PCM on my Windows Server 2016 VM (Hyper-V)?

**Comment by opcm** [comment]
it is installation issue for WDK build tools. There are many hits in Google for this error message...

**Comment by opcm** [comment]
I am going to close the issue because it is not specific to PCM.
