### ISSUE TITLE
Conditional Compile

### ISSUE THREAD

**Issue by baketchum** [opcm/pcm#236]
https://github.com/opcm/pcm/blob/3815f617f9627eef5905d503268c87d5028ffeeb/Makefile#L143

These two lines could be wrappted in: ifeq ($(UNAME), Linux)

**Comment by opcm** [comment]
@baketchum you are right. Do you want to send a PR or you want me to change it?

**Comment by baketchum** [comment]
There are few clang warnings that could be addressed. Shall I include
those in a PR or need they be separate?

**Comment by opcm** [comment]
better include them in a different PR.

**Comment by opcm** [comment]
merged
