### ISSUE TITLE
Can't build on OS X 10.12.4 with XCode 8.3

### ISSUE THREAD

**Issue by Olsonist** [opcm/pcm#24]
The _kextload.sh_ script in MacMSRDriver is sincerely wedged.

`cp -R Build/Products/Release/PcmMsrDriver.kext /tmp/.`

_build_ should be lowercase (my OSX filesystem is case sensitive) and _Products_ should be removed.

`cp -R build/Release/PcmMsrDriver.kext /tmp/.`

Also, the file is a DOS file meaning that it has carriage returns and linefeeds. This confuses bash.

```
: command not found 2:
mv: rename /tmp/PcmMsrDriver.kext to /System/Library/Extensions\r: No such file or directory
chown: /System/Library/Extensions/PcmMsrDriver.kext\r: No such file or directory
 failed to load - (libkern/kext) not found; check the system/kernel logs for errors or try kextutil(8).
make: *** [install] Error 71

```
This is the od -c dump of _kextload.sh_:

```
0000000    #   !   /   u   s   r   /   b   i   n   /   e   n   v       b
0000020    a   s   h  \r  \n  \r  \n   c   p       -   R       b   u   i
```

I do not as yet have a working PCM on OSX compiled from the github zip file.

**Comment by Thireus** [comment]
I can confirm. As an alternative, you can run the commands manually:

```
cp -R ./build/Release/PcmMsrDriver.kext /tmp/.
mv /tmp/PcmMsrDriver.kext /System/Library/Extensions/
sudo mv /tmp/PcmMsrDriver.kext /System/Library/Extensions/
sudo chown -R root:wheel /System/Library/Extensions/PcmMsrDriver.kext
sudo kextload /System/Library/Extensions/PcmMsrDriver.kext
```

**Comment by opcm** [comment]
fixed in the master branch now
