### ISSUE TITLE
Enhancement request: adding iterations to the tools.

### ISSUE THREAD

**Issue by shahar-fleischman** [opcm/pcm#243]
Hi,

Right now the tools allow you to set the time interval between samples/prints.
If I want to run it for just a few iterations and not permanently, there is no option.
The only workaround was to use [timelimit](https://packages.ubuntu.com/xenial/utils/timelimit) tool that sends a kill to the tool after the time limit arrived.

thanks.

**Comment by opcm** [comment]
did you check the -i=x option? x is the number of iterations

**Comment by shahar-fleischman** [comment]
Thanks for the quick reply :) 

In my version there is no such option:
`WARNING: unknown command-line option: "-i". Ignoring it.`
This is the version I've used:
`pcm-0-lp151.218.1.x86_64.rpm`

**Comment by opcm** [comment]
what pcm utility did you run? where did you get this rpm?

you can try the latest from https://download.opensuse.org/repositories/home:/opcm/

**Comment by opcm** [comment]
ok. pcm-numa currently does not support this option. I am accepting it as a feature request.
