### ISSUE TITLE
Support for i5-10400

### ISSUE THREAD

**Issue by recycledx** [opcm/pcm#269]
Hello,
current version reports i5-10400 as unsupported. I believe this is due to bug in https://github.com/opcm/pcm/blob/0a178ec2573821e3c08beb6bd76808ebb912bc76/cpucounters.h#L1246 when the actual model of the Comet Lake (non-U variants) is 165. -U variants have, I believe, model 142.
Changing CML constant from 166 to 165 solves the problem.

Modified version results in
`
Detected Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz "Intel(r) microarchitecture codename Kabylake" stepping 5 microcode level 0xca
`

Did not check everything, but at least `pcm.x` works - however processor is reported as Kaby Lake uarch (see above), but this is just minor inconsistency (due to https://github.com/opcm/pcm/blob/0a178ec2573821e3c08beb6bd76808ebb912bc76/cpucounters.cpp#L2064).

Thanks.

**Comment by opcm** [comment]
@recycledx thanks for submitting this issue. The 166 cpu model was reported for i7-10710U in https://github.com/opcm/pcm/issues/249 . We will add your model soon too. Until then you are good with the workaround you have found.

**Comment by opcm** [comment]
this is the best source I found https://download.01.org/perfmon/mapfile.csv
but it maps all KBL, CML, etc to SKL

**Comment by recycledx** [comment]
I believe this table is based on [Intel software dev manul, vol 4 - MSRs](https://software.intel.com/content/www/us/en/develop/download/intel-64-and-ia-32-architectures-software-developers-manual-volume-4-model-specific-registers.html), pages 2-1 through 2-2

**Comment by opcm** [comment]
thanks a lot for the pointer!

**Comment by opcm** [comment]
@recycledx  the CPU models have been just added in the recent master branch and https://github.com/opcm/pcm/releases/tag/202101 release

**Comment by opcm** [comment]
should this issue be closed?

**Comment by recycledx** [comment]
works for me on FreeBSD 12.2
