### ISSUE TITLE
Question - About MSR Driver, is it Software Driver (Upper level filter driver)?

### ISSUE THREAD

**Issue by anurag-daware** [opcm/pcm#27]
I am learning about windows driver, with this project,
Trying to understand the type of the driver.
From my understanding while reading MSDN docs, is this Software driver (Upper level filter driver)?
Also why doesn't it show up in device manager?

**Comment by opcm** [comment]
msr.sys is not an upper level filter driver.
Also this is not a right forum for generic Windows driver development questions. I think Microsoft forums are a more appropriate place.
