### ISSUE TITLE
Question: PCIe Eventgroups

### ISSUE THREAD

**Issue by HelgeBrands** [opcm/pcm#270]
Hi,
I have a question to readout PCI-E data. In an earlier version there were two functions used (programPCIeCounters and programPCIeMissCounters) now there are  programPCIeEventGroup/getPCIeCounterData. For me it is not completly clear where and how to setup these enventgroups. In the example code these Platform stuff is now used (getPlatform). This is not in the main library only in the examples. 
Can you give me some hints how to generate these groups.

Thanks for your help
Best regards
    Helge Brands

**Comment by opcm** [comment]
the event groups are setup here: https://github.com/opcm/pcm/blob/0a178ec2573821e3c08beb6bd76808ebb912bc76/pcm-pcie.h#L368 

hope this helps..
