### ISSUE TITLE
[Question] Pinning PCM to specific cores (PCM is not honoring isolcpus)

### ISSUE THREAD

**Issue by hoax-killer** [opcm/pcm#273]
Hi,

I did not see a mailing list hence putting up the question here.

I have 48 cores in my machine, and isolated 46 cores by adding `isolcpus=2-47` as kernel param.
When I run PCM, it still runs on all the 48 cores. Is there a way for me to pin PCM to specific cores or simply honor the cores that have been configured to be isolated from kernel scheduling?

Thanks.

**Comment by opcm** [comment]
I there is a discussion tab in the repo. Transferring the question there.

I have little experience with isolcpus. Could you please post PCM output with isolcpus here?
