### ISSUE TITLE
Windows10, pre-compiled bins, how to filter  Core    C-state distribution and Package C-state distribution section display?

### ISSUE THREAD

**Issue by shamashii** [opcm/pcm#282]
I use pcm to observe l3 cache hit rate, they are displayed before Core    C-state distribution section
 It seems on my locale, these symbols  ┌ ┐ └ ┘─ are wrong graph displayed, and cause whole **exe stuck**, no scroll, have to ctrl-c
The solution currently is use old console, is there any way overcome this?

    normal display:                      ┌───────────────────────────────────────────────────────────────────────────────┐
 Core    C-state distribution│0000000000000111111111111111111111111111111111111111111111377777777777777777777│
                             └───────────────────────────────────────────────────────────────────────────────┘
                             ┌────────────────────────────────────────────────────────────────────────────────┐
 Package C-state distribution│00000000000000000000000000000000000000000000000000000000000000000000000000000000│
                             └────────────────────────────────────────────────────────────────────────────────┘

stuck display:

                             谀哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪
哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪目
 Core    C-state distribution?00000000000000000000000000000000000000001111111111
11111111111111111111111111111
                             滥哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪
哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪馁
                             谀哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪
哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪目
 Package C-state distribution?00000000000000000000000000000000000000000000000000
00000000000000000000000000000
                             滥哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪
哪哪哪哪哪哪哪哪哪哪哪哪哪哪哪馁

or, I want just display cache hit rate section, is there any way?

**Comment by opcm** [comment]
@shamashii thanks for reporting this. What console and locale is it? I am thinking about a way to detect it in the code. As a workaround I have pushed a change in a new branch (https://github.com/opcm/pcm/tree/opcm-w-a-win-console-bug) that does not print these stats. You can try the binaries (https://ci.appveyor.com/api/buildjobs/evdtt7nkcw682igx/artifacts/pcm-all.zip) built from this branch.

**Comment by shamashii** [comment]
> 
> 
> @shamashii thanks for reporting this. What console and locale is it? I am thinking about a way to detect it in the code. As a workaround I have pushed a change in a new branch (https://github.com/opcm/pcm/tree/opcm-w-a-win-console-bug) that does not print these stats. You can try the binaries (https://ci.appveyor.com/api/buildjobs/evdtt7nkcw682igx/artifacts/pcm-all.zip) built from this branch.

Win native cmd, zh-cn , and new builds worked like a charm in your last link, thank you.
