### ISSUE TITLE
CFLAGS/CXXFLAGS environment variables ignored when building some object files

### ISSUE THREAD

**Issue by ZaWertun** [opcm/pcm#284]
If I define custom CXXFLAGS and CFLAGS via env. variables some object files still will be building with default ones.
There is list: daemon.o, main.o.

Make output:
```
Building file: ../daemon.cpp
Invoking: C++ Compiler
g++ -O0 -g3 -Wall -c -fmessage-length=0 -Wno-unknown-pragmas -std=c++11 -MMD -MP -MF"daemon.d" -MT"daemon.d" -o "daemon.o" "../daemon.cpp"
Finished building: ../daemon.cpp

Building file: ../main.cpp
Invoking: C++ Compiler
g++ -O0 -g3 -Wall -c -fmessage-length=0 -Wno-unknown-pragmas -std=c++11 -MMD -MP -MF"main.d" -MT"main.d" -o "main.o" "../main.cpp"
Finished building: ../main.cpp
```

And both CFLAGS and CXXFLAGS was set to
```
-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
```
(default for the Fedora packages).

**Comment by ogbrugge** [comment]
The change itself is simple, we'd need to adjust the CFLAGS and CXXFLAGS in the makefile(s) but we're not necessarily willing to support most of the flags you are using nor do we deem them useful. Just saying that if you use flags that are not default then do not expect support unless you are willing to submit patches for any fallout this will bring.

**Comment by xvitaly** [comment]
Fedora package **must** use all distribution-wide flags.

**Comment by ogbrugge** [comment]
As i said, i am not against the change and it is high time we fix the Makefiles but after just now discussing this with my colleague I am still not sure how we should deal with the fallout of the additional options, i would like to think some more about it and do some checking

**Comment by ogbrugge** [comment]
Some additional fixups would still be needed but with your C/CXXFLAGS it would now look like this ( i had to remove some specific redhat options, i do not have them on my suse sandbox) but i'll submit a patch when i am done verifying:

Building file: ../daemon.cpp
Invoking: C++ Compiler
g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -Wall -g -O3 -Wno-unknown-pragmas -fPIC -std=c++11 -DPCM_USE_PERF -Wextra -DPCM_USE_PERF -O2 -g3 -Wall -c -fmessage-length=0 -Wno-unknown-pragmas -std=c++11 -MMD -MP -MF"daemon.d" -MT"daemon.d" -o "daemon.o" "../daemon.cpp"
Finished building: ../daemon.cpp

Building file: ../main.cpp
Invoking: C++ Compiler
g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -Wall -g -O3 -Wno-unknown-pragmas -fPIC -std=c++11 -DPCM_USE_PERF -Wextra -DPCM_USE_PERF -O2 -g3 -Wall -c -fmessage-length=0 -Wno-unknown-pragmas -std=c++11 -MMD -MP -MF"main.d" -MT"main.d" -o "main.o" "../main.cpp"
Finished building: ../main.cpp

**Comment by opcm** [comment]
done: https://github.com/opcm/pcm/pull/285 kudos to @ogbrugge

**Comment by ogbrugge** [comment]
Ok, will make a patch for that, can you give me arguments you use for it so i can test with that?

**Comment by opcm** [comment]
@xvitaly ok. LDFLAGS was not mentioned before.

**Comment by xvitaly** [comment]
```
  CFLAGS="${CFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules}" ; export FFLAGS ; 
  FCFLAGS="${FCFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ; 
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld }" ; export LDFLAGS ; 
  LT_SYS_LIBRARY_PATH="${LT_SYS_LIBRARY_PATH:-/usr/lib64:}" ; export LT_SYS_LIBRARY_PATH ; 
  CC="${CC:-gcc}" ; export CC ; 
  CXX="${CXX:-g++}" ; export CXX
```

**Comment by ogbrugge** [comment]
I screwed up the linker command, used CXXFLAGS before, should have used LDFLAGS there, fixed, will submit in a second and let it build.

**Comment by opcm** [comment]
@xvitaly fixed and merged: https://github.com/opcm/pcm/pull/287

**Comment by xvitaly** [comment]
> fixed and merged: #287

Not fixed. CFLAGS and LDFLAGS must be used together.

**Comment by ogbrugge** [comment]
At this point i more am inclined to make sure all makefiles do not pick up CXXFLAGS, CFLAGS and LDFLAGS from the outside by reverting and setting the variables to empty before even filling them with our options. This bits and pieces treatment is annoying.

I'll go through the Makefile one last time and try to adjust the link commands to honor C/CXXFLAGS and LDFLAGS for the link commands because from a quick look the combination of CXX- and LD-FLAGS lacks in many places...

**Comment by xvitaly** [comment]
@ogbrugge You can just switch to CMake or Meson. It will do everything automatically.

**Comment by ogbrugge** [comment]
I'm now running into issues related to your -Wl,--as-needed linker option, with it several apps no longer link and give errors regardign missing pthread_create despite having -lpthread in the link line. If i remove the -Wl,--as-needed option it links fine. Without setting CXXFLAGS and LDFLAGS to your options all works fine as well.

**Comment by ogbrugge** [comment]
https://stackoverflow.com/questions/56368771/undefined-reference-with-link-time-optimization-and-as-needed-ld-flag

I'm possibly running into this linker bug...

**Comment by xvitaly** [comment]
Yes, you must explicitly link with all libraries used in project.

**Comment by ogbrugge** [comment]
-lpthread is there, the linker after upgrading is now working so it was the mentioned linker bug... Just to make sure I adapted the Makefile to include -pthread to CFLAGS and CXXFLAGS (for Linux only) and changed -pthread in LIB to -lpthread as it should be.

While at it, I fixed CXXFLAGS to no longer include CFLAGS, it lead to all options being duplicated when external CFLAGS and CXXFLAGS are very similar.

**Comment by ogbrugge** [comment]
If you want to try this out you can try the respect_cxxflags branch

**Comment by opcm** [comment]
@xvitaly please have a look: https://github.com/opcm/pcm/pull/288

**Comment by xvitaly** [comment]
> @xvitaly please have a look: #288

LGTM now.

**Comment by opcm** [comment]
merged
