### ISSUE TITLE
11th Gen Intel core unsupported.

### ISSUE THREAD

**Issue by oldcityustc** [opcm/pcm#298]
Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, unknown, Centerton, Baytrail, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Cherrytrail, Avoton, Skylake U/Y, Broadwell-EP/EX, Skylake-SP, Cascade Lake-SP, Broadwell-DE, Knights Landing, Apollo Lake, Skylake, Denverton, Icelake-SP, Icelake, Snowridge, Tiger Lake, Kabylake/Whiskey Lake, Kabylake, Comet Lake). CPU model number: 167 Brand: "11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz"

Detected 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz "Intel(r) microarchitecture codename unknown" stepping 1
Unsupported processor model (167).

**Comment by opcm** [comment]
Thanks for reporting this issue. Could you please try the following workaround until a clean patch is available: please replace 126 with 167 in this line
https://github.com/opcm/pcm/blob/20bf7a6eb605c5864da97d9313917ce5b3b94feb/cpucounters.h#L1315

**Comment by oldcityustc** [comment]
Thank you for your quick reply.
I modify the source code as you described. 
but still meet some error. 


root@z590:/home/pcm# modprobe msr
root@z590:/home/pcm# ./pcm-memory.x

 Processor Counter Monitor: Memory Bandwidth Monitoring Utility  ($Format:%ci ID=%h$)

 This utility measures memory bandwidth per channel or per DIMM rank in real-time

Linux arch_perfmon flag  : yes
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Number of physical cores: 8
Number of logical cores: 16
Number of online logical cores: 16
Threads (logical cores) per physical core: 2
Num sockets: 1
Physical cores per socket: 8
Last level cache slices per socket: 8
Core PMU (perfmon) version: 5
Number of core PMU generic (programmable) counters: 8
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 4
Width of fixed counters: 48 bits
Nominal core frequency: 3600000000 Hz
IBRS enabled in the kernel   : yes
STIBP enabled in the kernel  : no
The processor is not susceptible to Rogue Data Cache Load: yes
The processor supports enhanced IBRS                     : yes
Package thermal spec power: 125 Watt; Package minimum power: 0 Watt; Package maximum power: 0 Watt;
INFO: Linux perf interface to program uncore PMUs is NOT present

Detected 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz "Intel(r) microarchitecture codename Icelake" stepping 1 microcode level 0x1b
Unsupported processor model (a7).
For processor-level memory bandwidth statistics please use pcm.x
Cleaning up
 Zeroed uncore PMU registers
root@z590:/home/pcm# git diff
diff --git a/cpucounters.h b/cpucounters.h
index 5721a2c..2b9fb90 100644
--- a/cpucounters.h
+++ b/cpucounters.h
@@ -1312,7 +1312,7 @@ public:
         KBL_1 = 142,
         CML = 166,
         CML_1 = 165,
-        ICL = 126,
+        ICL = 167,
         ICL_1 = 125,
         TGL = 140,
         TGL_1 = 141,
root@z590:/home/pcm#

**Comment by ogbrugge** [comment]
pcm-memory is not supported on desktop processors as far as i know, only
works on xeon.

**Comment by opcm** [comment]
https://github.com/opcm/pcm/blob/master/FAQ.md#q6

**Comment by oldcityustc** [comment]
Hi，
      Thank you for information.
       Yes, I am trying to run pcm-memory on desktop PC. As it is unsupported, I will shift to the intel server to run it.

Huamin

**Comment by opcm** [comment]
RKL is supported now
