### ISSUE TITLE
failed to load PcmMsrDriver.kext on OS X

### ISSUE THREAD

**Issue by Olsonist** [opcm/pcm#30]
I am able to build pcm now. However, the kext will not load. I am running 10.12.4 on a 2014 MacBook Pro, XCode 8.3. I generally compile with llvm and nasm. So my XCode configuration is out of the box stock.

After _sudo sh_:

```
./kextload.sh

/System/Library/Extensions/PcmMsrDriver.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).

```
Also,

```
kextutil -i /System/Library/Extensions/PcmMsrDriver.kext
Diagnostics for /System/Library/Extensions/PcmMsrDriver.kext:
Code Signing Failure: not code signed
/System/Library/Extensions/PcmMsrDriver.kext appears to be loadable (not including linkage for on-disk libraries).
Untrusted kexts are not allowed
ERROR: invalid signature for com.intel.driver.PcmMsr, will not load
```

Nothing of interest in the logs.

**Comment by bo01ean** [comment]
You have to allow unsigned kexts:
https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/KernelExtensions/KernelExtensions.html

Or sign the kext.

Allowing unsigned kexts is far easier.

**Comment by Olsonist** [comment]
Thanks. I'm running 10.12 Sierra, so _sudo nvram boot-args="kext-dev-mode=1"_ won't work.

Rebooting to recovery mode (reboot, command-option-r), starting a shell, csrutil disable and reboot does work.

**Comment by Olsonist** [comment]
I'm submitting a pull request for MAC_HOWTO.txt to document how to do this:

kext Signing
------------
If kextload.sh says the kext is "not loadable", you need to either disable System Integrity Protection or sign the kext.
You can disable SIP by rebooting into Recovery (reboot, command-option-R), opening a shell, csrutil disable and reboot again.
Signing a kext is more involved. You can't self-sign and will first need a Developer ID (https://developer.apple.com/contact/kext/)
You will then sign your kext with codesign(1).

**Comment by opcm** [comment]
@Olsonist I do not see your pull request. Could you please create one (again)?

**Comment by kzjeef** [comment]
For anyone meet same issue,

you can follow the instruction in this link to disable kext protection in your machine:

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html#//apple_ref/doc/uid/TP40016462-CH5-SW1
