### ISSUE TITLE
pcm-pcie reports invalid counts

### ISSUE THREAD

**Issue by NAtre** [opcm/pcm#306]
Hello,

I'm trying to use pcm-pcie to understand the PCIe characteristics of my network hardware, but the tool seems to be reporting invalid values for several fields. For instance, here's the output of `sudo ./pcm-pcie.x -e` on a dual-socket Intel Xeon E5-2620 (Broadwell) server running Ubuntu 18.04 (help block elided for brevity).

![pcm-pcie](https://user-images.githubusercontent.com/6562132/123995725-a0277c80-d99c-11eb-8f28-628d3a0ea477.png)

In the first output block, PCIRdCur reports "18446744 T" (`2^64 - 1`) hits for socket #0, with 0 total accesses. The same value seems to show up in several places, e.g. in this run:

![pcm-pcie-2](https://user-images.githubusercontent.com/6562132/123996918-d74a5d80-d99d-11eb-9216-5e7c5d22d0f3.png)

The help block indicates that certain fields (PCIeReadCur, RFO, CRd) "may report 0" if the BIOS is improperly configured, but this also shows up in other fields (e.g. ItoM, PRd), suggesting that it's a different issue. I've tried using the tool on two other machines in our cluster (same server configuration) without any luck. Any insights on what's causing this or how to fix it would be greatly appreciated. Thank you!

Best Regards,
Nirav

**Comment by opcm** [comment]
How often do you see such samples, all the time or very rarely (e.g. once a day?) cc @ilia-kurakin

**Comment by NAtre** [comment]
Thank you for the quick turnaround! Unfortunately, these show up all the time; over the course of 60s (updates 1s apart), 48/60 output blocks had at least one occurrence of the invalid sample

**Comment by ilia-kurakin** [comment]
Nirav, thanks for reporting the issue. The fix will be included to the next release. Current issue workaround is 
`pcm-pcie.x -e | sed 's/18446744 T/0/g'`

**Comment by opcm** [comment]
thanks a lot @ilia-kurakin !
