### ISSUE TITLE
pcm docker container exits with assertion error

### ISSUE THREAD

**Issue by MusinDanil** [opcm/pcm#313]
I followed docker pcm launch [instruction](https://github.com/opcm/pcm/blob/master/DOCKER_README.md)
But soon after container starts it stops. And only messages in `docker logs` are 
```
Detected a hypervisor/virtualization technology. Some metrics might not be available due to configuration or availability of virtual hardware features.
Linux arch_perfmon flag  : yes
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
pcm-sensor-server.x: cpucounters.cpp:284: pcm::uint32 pcm::build_bit_ui(pcm::uint32, pcm::uint32): Assertion `end <= 31' failed.
```

**Comment by ogbrugge** [comment]
Can you write a little more about your processor?

@opcm , is that docker image up to date? The assert is no longer on line 284 but on line 316.

**Comment by opcm** [comment]
@MusinDanil please pull/update your container

**Comment by MusinDanil** [comment]
Pardon me, i gave you wrong logs. Here are correct ones.
```
Detected a hypervisor/virtualization technology. Some metrics might not be available due to configuration or availability of virtual hardware features.
Linux arch_perfmon flag  : yes
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
pcm-sensor-server.x: cpucounters.cpp:316: pcm::uint32 pcm::build_bit_ui(pcm::uint32, pcm::uint32): Assertion `end <= 31' failed.
```
About hardware:
2x Intel Xeon E5-2699 v3
Installed in ProLiant DL380 Gen9 server

**Comment by opcm** [comment]
thanks for reporting. I have seen a similar (already fixed) error inside a VMWare virtual machine. Are you running it inside a VMWare virtual machine?

**Comment by MusinDanil** [comment]
Yes it appears i run it on VMware virtual machine. Should it work in this case?

**Comment by opcm** [comment]
even if the assertion will be fixed it will most likely end up in failing the check for required PMU level. VMWare does not expose access to hardware performance monitoring units at the level that PCM requires.

**Comment by MusinDanil** [comment]
Thanks a lot for your help, then i am closing issue
