### ISSUE TITLE
`const` violations with string literals in `winpmem.h`

### ISSUE THREAD

**Issue by BenHetherington** [opcm/pcm#328]
It seems like 5dc7f65 introduced some header-side code to `winpmem.h`, and in doing so, introduced a few issues where string literals are being passed to `LogError(TCHAR*)`, which takes a *mutable* `TCHAR` pointer, as opposed to the `const` pointer that string literals are initialised as.

When including PCM in a project that's compiled under MSVC with `/permissive-` (which is the default for new projects, and the default when compiling under C++20), it causes this `const` violation to be flagged as an error.

I'm not sure if there are more `const`ness issues around in PCM's headers (let alone in its `.cpp` files), but I figured I'd at least report this one!

**Comment by opcm** [comment]
@BenHetherington thanks a lot for reporting this issue. Would you be able to contribute a pull request with a fix?

**Comment by BenHetherington** [comment]
Sure, I'll see if I can look into this tomorrow.

**Comment by opcm** [comment]
thanks!
