### ISSUE TITLE
Broken links in log messages

### ISSUE THREAD

**Issue by alexandrnikitin** [opcm/pcm#33]
Launching `pcm-core.exe` from CI artifacts on Win 10 gives me this error:
```
ERROR: winpmem_64.sys not found in current directory. Download it from https://volatility.googlecode.com/svn-history/r2813/branches/scudette/tools/windows/winpmem/binaries/winpmem_64.sys .
```

The link doesn't exist anymore. Related piece of code: https://github.com/opcm/pcm/blob/456ff2fd8734fc1b51114d9e5bf92b6b42fb588e/client_bw.cpp#L52

**Comment by opcm** [comment]
you can download the file from https://github.com/google/rekall/tree/master/tools/pmem/resources/winpmem
Any chance you can create a pull request with a fix?

**Comment by alexandrnikitin** [comment]
Thanks for your reply. Sure, I'll do it.

**Comment by opcm** [comment]
thanks!!
