### ISSUE TITLE
Expose DRAM_GT_REQUESTS and DRAM_IA_REQUESTS

### ISSUE THREAD

**Issue by jrmuizel** [opcm/pcm#344]
Currently `pcm` only exposes DRAM_IO_REQUESTS. It would be valuable if it also exposed DRAM_GT_REQUESTS and DRAM_IA_REQUESTS so that it would clearer what the breakdown of memory bandwidth is.

**Comment by opcm** [comment]
thanks! accepting it as a feature request

**Comment by opcm** [comment]
this has been implemented in the master branch recently
