### ISSUE TITLE
How to build msr.sys in production sign mode in VS2015

### ISSUE THREAD

**Issue by anurag-daware** [opcm/pcm#35]
I have 3-4 systems, where I am running pcm.exe with msr.sys built with vs2015.
It is running fine, today I setup new system with Windows1064-RS2 RTM
and I am getting error - 
You must have signed msr.sys driver in your current directory and have administrator rights to run this program
Any idea why on one single machine it is giving signature error?

**Comment by anurag-daware** [comment]
I have found this - On the other systems where this msr.sys worked, had testsigning ON. But my new system has testsigning OFF. VS2015 project builds msr.sys in Test Sign mode. Does anyone here know how can we build in production sign mode?

**Comment by opcm** [comment]
I found a reference for you (https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/signing-a-driver-for-public-release): _"you must sign the package with a certificate that you obtain from a trusted certification authority like VeriSign. For more information, see Get a VeriSign Certificate. You will also need a cross certificate, which is provided by Microsoft."_
