### ISSUE TITLE
traps: pcm-sensor-serv general protection fault

### ISSUE THREAD

**Issue by opriegov** [opcm/pcm#368]
we're having the following Issue where the pcm-sensor-serv is failing constantly over and over, and reinitializing itself:

[  106.318686] traps: pcm-sensor-serv[8542] general protection fault ip:7f638b3f9967 sp:7ffe5e7434b0 error:0 in libc-2.32.so[7f638b3f9000+14f000]
[  119.528059] traps: pcm-sensor-serv[9249] general protection fault ip:7f5cd4b4b967 sp:7ffdee8b8de0 error:0 in libc-2.32.so[7f5cd4b4b000+14f000]
[  120.933554] IPv6: ADDRCONF(NETDEV_CHANGE): cali2df86566d7a: link becomes ready
[  120.933657] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  120.933900] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  131.925393] traps: pcm-sensor-serv[10349] general protection fault ip:7fedfd96e967 sp:7fff69236890 error:0 in libc-2.32.so[7fedfd96e000+14f000]
[  160.934242] traps: pcm-sensor-serv[11586] general protection fault ip:7f07b4dd2967 sp:7ffdfaa09df0 error:0 in libc-2.32.so[7f07b4dd2000+14f000]
[  201.891439] traps: pcm-sensor-serv[13413] general protection fault ip:7fed5b2a2967 sp:7ffd3c61bcb0 error:0 in libc-2.32.so[7fed5b2a2000+14f000]
[  289.930073] traps: pcm-sensor-serv[16510] general protection fault ip:7fd93744b967 sp:7ffda826bab0 error:0 in libc-2.32.so[7fd93744b000+14f000]
[  453.934717] traps: pcm-sensor-serv[22956] general protection fault ip:7f9c61caa967 sp:7ffc2f1ee890 error:0 in libc-2.32.so[7f9c61caa000+14f000]
[  764.933730] traps: pcm-sensor-serv[34781] general protection fault ip:7fcf65aef967 sp:7fff3f085400 error:0 in libc-2.32.so[7fcf65aef000+14f000]
[ 1078.925888] traps: pcm-sensor-serv[46355] general protection fault ip:7f99d5874967 sp:7ffcb7cdf1f0 error:0 in libc-2.32.so[7f99d5874000+14f000]
[ 1387.949488] traps: pcm-sensor-serv[58417] general protection fault ip:7fd0b4751967 sp:7ffec6d2cf70 error:0 in libc-2.32.so[7fd0b4751000+14f000]
[ 1693.953127] traps: pcm-sensor-serv[69686] general protection fault ip:7fa973988967 sp:7ffd16e730e0 error:0 in libc-2.32.so[7fa973988000+14f000]
[ 2007.982202] traps: pcm-sensor-serv[81593] general protection fault ip:7f7cb24f6967 sp:7ffcff21eda0 error:0 in libc-2.32.so[7f7cb24f6000+14f000]

for further information on tracking, please contact me.
Oscar Priego.

**Comment by ogbrugge** [comment]
The output you post is useless, it shows an error in glibc but I can’t fix that. Not sure what system you are running on and how you start pcm-sensor-server or which version it is. Please provide as much information as possible including all output from the program if you run it as root from a command line.

**Comment by opcm** [comment]
Stale issue. Please reopen when details will be available
