### ISSUE TITLE
Counters exposed by pcm-sensor-server

### ISSUE THREAD

**Issue by saswat0** [opcm/pcm#369]
Can I run all pcm services(pcm-latency, pcm-iio, pcm-pcie, etc.) along with pcm-sensor-server? I wish to view L1 cache misses and other counter values as well via my prometheus server. Is there any way to achieve the same?
Thanks in advance

**Comment by ogbrugge** [comment]
If they use the PMU then no, if they are using free running counters then yes but I am not too familiar with the inner working of pcm-latency, -iio and -pcie. @opcm can certainly tell you what is possible. If some of these tools are using free running counters then perhaps some code changes in pcm-sensor-server could allow the collection of all this information at the same time but do not get your hopes up, I do not have time to implement that at this point in time even if it is possible.

**Comment by opcm** [comment]
some of the utilities do not use the same PMUs as pcm-sensor-server but we do not support this mode of operation.

**Comment by saswat0** [comment]
Alright. Got it
Thanks @opcm @ogbrugge
