### ISSUE TITLE
Using PCM API on parallel programs

### ISSUE THREAD

**Issue by yushangdi** [opcm/pcm#378]
I have the following code that runs in parallel and uses all cores. It finishes in 0.674s. However, if I uncomment the `PCM *m = PCM::getInstance();` line, it runs in 3.94s and I observe that it only uses a single thread from `top`. I'm wondering how I can use the PCM to monitor a parallel program? Thanks!

```cpp
#include "cpucounters.h"
#include <omp.h>
#include "gettime.h"

using namespace std;
using namespace pcm;
int main() {
    // PCM *m = PCM::getInstance();
    timer t;t.start();
    size_t n = 10000000;
    size_t *arr = (size_t *)malloc(96* n * sizeof(size_t));
    int numThreads = 96;
    #pragma omp parallel
    {
        int ThreadID = omp_get_thread_num();
        for(size_t x= n * ThreadID; x < (ThreadID + 1) * n ; x+= 1){
          arr[x] = x;
        }
    }
    free(arr);
    t.reportTotal("total time");
}
```

Here is how I compiled it:

```cmake
add_executable(bench main.cpp)  # be sure there's exactly one main() function in the source files
target_include_directories(bench PRIVATE ${PCM_DIR}/src)
target_link_libraries(bench PUBLIC OpenMP::OpenMP_CXX)
target_compile_definitions(bench PRIVATE PCM_DYNAMIC_LIB) # -DPCM_DYNAMIC_LIB
target_link_libraries(bench PRIVATE Threads::Threads dl pcm)  # -pthread -ldl -lpcm
```

I also observe the same issue when I run ` pcm-numa --external_program myprogram -n 48`. Even if my program is parallel, it only runs on a single thread.

**Comment by yushangdi** [comment]
Even if I just have a function like below without calling it, my program would still become sequential, and I would see "=====  Processor information  ===== ..." outputs.

```
void test(){
    pcm::PCM *m = pcm::PCM::getInstance();
}
```

**Comment by ogbrugge** [comment]
I'm not sure what causes this. What is the compiler and what is its version that are you using so i can perhaps try and replicate this behavior?

**Comment by yushangdi** [comment]
I'm using  g++ compiler (version 7.5), and the latest master branch of pcm. I was running on aws c.5 bare-metal machine on ubuntu 18.

**Comment by opcm** [comment]
thanks for reporting this issue. Could you please try the following temp workaround: in https://github.com/opcm/pcm/blob/58039287e0ee63edcaa60bdbf837d536e4e417da/src/cpucounters.cpp#L177

please change the default value of the last parameter ("bool restore_") from false to true. Please let us know if this resolves the issue.

**Comment by mjguzik** [comment]
Like so?

`diff --git a/src/cpucounters.cpp b/src/cpucounters.cpp
index b4a66a9..3912c3d 100644
--- a/src/cpucounters.cpp
+++ b/src/cpucounters.cpp
@@ -136,7 +136,7 @@ class TemporalThreadAffinity  // speedup trick for Linux, FreeBSD, DragonFlyBSD,
     const bool restore;
 
 public:
-    TemporalThreadAffinity(uint32 core_id, bool checkStatus = true, const bool restore_ = false)
+    TemporalThreadAffinity(uint32 core_id, bool checkStatus = true, const bool restore_ = true)
        : restore(restore_)
     {
         assert(core_id < 1024);
@@ -174,7 +174,7 @@ public:
     const bool restore;
 
 public:
-    TemporalThreadAffinity(const uint32 core_id, bool checkStatus = true, const bool restore_ = false)
+    TemporalThreadAffinity(const uint32 core_id, bool checkStatus = true, const bool restore_ = true)
         : set_size(CPU_ALLOC_SIZE(maxCPUs)), restore(restore_)
     {
         assert(core_id < maxCPUs);
@@ -212,7 +212,7 @@ public:
 #elif defined(_MSC_VER)
     ThreadGroupTempAffinity affinity;
 public:
-    TemporalThreadAffinity(uint32 core, bool checkStatus = true, const bool restore = false)
+    TemporalThreadAffinity(uint32 core, bool checkStatus = true, const bool restore = true)
        : affinity(core, checkStatus, restore)
     {
     }
`

This indeed fixes it.

**Comment by opcm** [comment]
@mjguzik thanks for checking and confirming. Would it be possible for you to submit a pull request with a quick fix?

**Comment by mjguzik** [comment]
I can do it if it helps sort it out in a timely manner, but this is a one-liner times three and I can't even take credit for it as you submitted 1/3rd :). Is there a problem for you to make the change?

**Comment by opcm** [comment]
@mjguzik You have done an extensive testing which is a larger effort and should get a credit. I would appreciate it if you can submit a pull request in a timely manner. It might take much longer on my side. Thank you.

**Comment by yushangdi** [comment]
Hi opcm and mjguzik, thank  you for working on this. I'm wondering how should I use this  TemporalThreadAffinity function? For example in my code in the original question? Thanks!

**Comment by opcm** [comment]
you don't need to use TemporalThreadAffinity in your code to get it fixed. This is a PCM internal class. You should only recompile your code with the latest PCM version from the master branch.
