### ISSUE TITLE
Possible to measure disk I/O waiting time for active CPUs?

### ISSUE THREAD

**Issue by gioannidis** [opcm/pcm#38]
There are already many tools to measure the % of the CPU waiting time during I/O operations, like `dstat`. Nevertheless, I am looking for a way to measure the waiting time of the **active cores**, pretty much in a way like `pcm.x` reports the utilization of cores in the active state.

I am running a compute-intensive map-reduce application, which is using only a few cores. Programs like `dstat` report only the total I/O waiting time across all cores (active and inactive), but I am suspecting that my active cores may be I/O bottlenecked.

**Comment by opcm** [comment]
unfortunately I am not aware of a CPU performance event that accounts stalls on I/O. I checked the recent core event list: https://download.01.org/perfmon/SKL/skylake_core_v30.json
