### ISSUE TITLE
programs spawned by pmc are bound to one thread

### ISSUE THREAD

**Issue by mjguzik** [opcm/pcm#380]
I presume this was not intentional. For example if one is to run pcm-core -- make -j $BIGNUM, it will all execute on one thread. Tested on FreeBSD and Linux.

**Comment by opcm** [comment]
This could be the same issue as in https://github.com/opcm/pcm/issues/378
Could you please try the temp workaround: https://github.com/opcm/pcm/issues/378#issuecomment-1059777310

**Comment by mjguzik** [comment]
Fixed with b941b03d93272a33458eeb941171684c2a396e32
