### ISSUE TITLE
Possible to collect > 4 custom events?

### ISSUE THREAD

**Issue by jhaberstro** [opcm/pcm#39]
I am interested in collecting more than 4 custom counter events at once. Is the current limitation of 4 in psx-core.x a limitation of the HW (I am using Skylake, for reference) or of the software?

I tried to take a gander myself and see that BasicCounterState defines Event0, Event1, Event2, and Event3, but grepping does not reveal where those values are set, so I can't easily asses why BasicCounterState only supports 4 events.

**Comment by opcm** [comment]
If Intel(r) Hyper-Threading technology is enabled than there are 4 hardware programmable core PMU counters available. If Intel(r) Hyper-Threading technology is disabled than there are 8 programmable core PMU counters available (but PCM supports only 4). The values are set [here](https://github.com/opcm/pcm/blob/master/cpucounters.cpp#L2988) via their union names. Patches/pull requests are welcome ;-)

**Comment by jhaberstro** [comment]
Thanks for the info! I'll see what I can do ;-). I have to get legal consent from my employer before contributing to open source.

Another question -- how fast could one reasonably sample the hardware? I'm interested in showing the Top-Down metrics over time.

**Comment by opcm** [comment]
Min sampling period of 10 ms is still reasonable with PCM. Pure kernel space tools can achieve lower sampling intervals.

**Comment by opcm** [comment]
Implemented in master branch
