### ISSUE TITLE
Some questions about the linear growth of pcm-iio test data

### ISSUE THREAD

**Issue by Crispig** [opcm/pcm#393]
Hi, thanks for your outstanding work. I am using pcm-iio to test the continuous transfer of PCIe and I observed that the values of IB write (bytes),IB read (bytes) are gradually increasing linearly during the test. But my experimental characteristic should be to maintain a stable transfer, and I got a stable result by making a difference to the adjacent values.
But after checking the source implementation I found that the test value is the difference before and after using getIIOCounterState() to get the time interval and it resets the variable. If the register count is not empty
What is the cause of this? Thank you very much!

![image](https://user-images.githubusercontent.com/56068245/160279606-febfe5a6-69fe-470c-a96c-e98f0a882a89.png)
![image](https://user-images.githubusercontent.com/56068245/160279643-eb53f593-395a-42b5-a9a4-5c782312ae2f.png)

**Comment by opcm** [comment]
the tool should output the number of events occured during the measurement period. Could you please share the raw output of the pcm-iio tool?

**Comment by Crispig** [comment]
Sampling every 0.05 seconds

**Comment by Crispig** [comment]
Sampling every 0.05 seconds

**Comment by Crispig** [comment]
Sampling every 0.05 seconds
[test_iio_0.05.txt](https://github.com/opcm/pcm/files/8360945/test_iio_0.05.txt)

**Comment by Crispig** [comment]
I'm very sorry, I found that it was a problem with my own image drawing code, the detection data should be fine, thank you very much for your answer！
