### ISSUE TITLE
not support Intel Eagle_Stream Saphire-Rapids SKU

### ISSUE THREAD

**Issue by wq2508** [opcm/pcm#396]
when it can support Eagle_Stream Saphire-Rapids SKU

currently have below ERROR ：
Processor Counter Monitor: Intel(r) Transactional Synchronization Extensions Monitoring Utility 
Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, unknown, Centerton, Baytrail, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Cherrytrail, Avoton, Skylake U/Y, Broadwell-EP/EX, Skylake-SP, Cascade Lake-SP, Broadwell-DE, Knights Landing, Apollo Lake, Skylake, Denverton, Icelake-SP, Icelake, Snowridge, Tiger Lake, Kabylake/Whiskey Lake, Alder Lake, Kabylake, Comet Lake, Rocket Lake). CPU model number: 143 Brand: "Genuine Intel(R) CPU 0000%@"
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).

**Comment by ogbrugge** [comment]
This is public github, we can't put NDA material here. If you are an Intel employee or a customer with the appropriate NDA then please contact us on our intel email addresses.
