### ISSUE TITLE
Access to Processor Counter Monitor has denied

### ISSUE THREAD

**Issue by neiblegy** [opcm/pcm#398]
Is there anything I can do to fix such problem,  run pcm-memory shows such error :

 Processor Counter Monitor: Memory Bandwidth Monitoring Utility  ($Format:%ci ID=%h$)

 This utility measures memory bandwidth per channel or per DIMM rank in real-time

=====  Processor information  =====
Linux arch_perfmon flag  : yes
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Max CPUID level          : 22
PCM Error: can't open MSR handle for core 0
Try no-MSR mode by setting env variable PCM_NO_MSR=1
Can not access CPUs Model Specific Registers (MSRs).
execute 'modprobe msr' as root user, then execute pcm as root user.

Detected Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz "Intel(r) microarchitecture codename Cascade Lake-SP" stepping 7

**Comment by opcm** [comment]
you need to run it as root on bare metal

**Comment by neiblegy** [comment]
> you need to run it as root on bare metal

I ran sudo ./bin/pcm-memory on ubuntu sys

~/pcm/build$ sudo ./bin/pcm-memory

 Processor Counter Monitor: Memory Bandwidth Monitoring Utility  ($Format:%ci ID=%h$)

 This utility measures memory bandwidth per channel or per DIMM rank in real-time


=====  Processor information  =====
Linux arch_perfmon flag  : yes
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Max CPUID level          : 22
PCM Error: can't open MSR handle for core 0
Try no-MSR mode by setting env variable PCM_NO_MSR=1
Can not access CPUs Model Specific Registers (MSRs).
execute 'modprobe msr' as root user, then execute pcm as root user.

Detected Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz "Intel(r) microarchitecture codename Cascade Lake-SP" stepping 7
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).

**Comment by neiblegy** [comment]
I run sudo modprobe msr first then pcm-memory is ok

**Comment by opcm** [comment]
ok. The issue can be closed (resolved)
