### ISSUE TITLE
Precompiled Kext for Mac OS X

### ISSUE THREAD

**Issue by astojanov** [opcm/pcm#4]
Hi Processor Counter Monitor Team,

I was wondering whether it would be possible to distribute a precompiled Kext module, for the Mac OS X driver for Intel PCM?

While on Windows we can access the MSR using `winring0` and `winpmem`, Mac OS X, particularly El Capitan and macOS Sierra, require a Developer ID certificate for signing Kexts. Therefore, to load the Kext, System Integrity Protection has to be disabled, leaving the Mac OS X system vulnerable.

While the code to hangle and interpret the MSR data undergoes improvements overtime, it seems that the interface to read the MSR data from the Mac OS X kernel does not change as often. Most of the files in the MacMSRDriver have copyrights headers dating from 2013. As such would it be possible to have a signed precompiled kernel, so it can be loaded without disabling Mac OS X System Integrity Protection? The users of Intel PCM will eventually have to recompile the client interface only, and work on a stable driver, that will be updated with new releases of Mac OS X.

Greetings,
Alen Stojanov

**Comment by aholtzma** [comment]
+1

**Comment by stoni** [comment]
+1

**Comment by opcm** [comment]
Hi,
please keep in mind that “Intel Performance Counter Monitor” is discontinued. The Processor Counter Monitor fork does not “belong” to Intel. Still some Intel engineers are contributing to Processor Counter Monitor but currently none of them has bandwidth or permission to publish signed drivers.
Thank you
