### ISSUE TITLE
pcm-memory monitors the throughput from iMC or Optane media?

### ISSUE THREAD

**Issue by xywoo-cs** [opcm/pcm#403]
Unlike DRAM, Optane PM has read and write buffers inside. And some requests will not introduce accesses on optane media. So I am wondering the PMM throughput get from `pcm-memory -pmm` includes those requests served by buffers?  

I make some tests, and it seems like the throughputs only include every requests to Optane media (*like read amplification*)?

Thanks!

**Comment by twillhal** [comment]
Your understanding is correct: pcm-memory monitors the reads and writes at the memory controllers, but not the traffic inside the Optane persistent memory module. The latter can be monitored with a different tool: Intel Persistent Memory Watch: https://github.com/intel/intel-pmwatch

**Comment by xywoo-cs** [comment]
Thank you so much!
