### ISSUE TITLE
ADL model 97 CPU is not supported by pcm-memory

### ISSUE THREAD

**Issue by alisov** [opcm/pcm#411]
INFO: Linux perf interface to program uncore PMUs is present

Detected 12th Gen Intel(R) Core(TM) i9-12900HK "Intel(r) microarchitecture codename Alder Lake" stepping 3 microcode level 0x41c
Unsupported processor model (97).
For processor-level memory bandwidth statistics please use 'pcm' utility
Cleaning up
 Closed perf event handles
 Zeroed uncore PMU registers

**Comment by opcm** [comment]
this is related to https://github.com/opcm/pcm/blob/master/doc/FAQ.md#q6

For processor-level memory bandwidth statistics on your CPU please use 'pcm' utility
