### ISSUE TITLE
Whether PCM supports Intel EagleStream CPU.

### ISSUE THREAD

**Issue by thebestsuper** [opcm/pcm#427]
Hi developers,
I am running the pcm tool on a machine with Intel EagleStream CPU, attached is the pcm tool log. I found out that pcm built on 2022/0820 doesn't support Intel EagleStream CPUs. Will PCM support Intel EagleStream CPUs in the future?

[PcmTool_20220820_log.txt](https://github.com/opcm/pcm/files/9392153/PcmTool_20220820_log.txt)

**Comment by opcm** [comment]
please refer to https://github.com/opcm/pcm/issues/396
