### ISSUE TITLE
Cannot measure cycles with Linux 4.11 and -DPCM_USE_PERF

### ISSUE THREAD

**Issue by soramichi** [opcm/pcm#44]
When  -DPCM_USE_PERF is enabled with the Linux kernel 4.11, pcm fails to measure the "Cycles", and "IPC" becomes "inf" due to a division by 0. If the line `CXXFLAGS += -DPCM_USE_PERF` is commented-out, it works perfectly.

My environment is as follows.
- CPU: Core i5-6400 (Skylake)
- distro: Debian GNU/Linux testing (code name ["buster"](https://www.debian.org/releases/testing/), next release of the current stable "stretch")
- kernel: 4.11.0-1-amd64 (distributor's version)
- gcc:  6.4.0 20170704 (Debian 6.4.0-1)
- pcm: commit 28514436873c48e18fef4d5b676436f52f5bddfa

Because `$ sudo perf stat -e cycles` gives correct results in the same environment, I guess the reason is not a bug of the kernel but a mis-configuration from the pcm side, possibly stemming from recent changes to the kernel code.

**Comment by soramichi** [comment]
Update: I built various kernel versions (using the `.config` provided by debian) and found the following.

- 4.10 doesn't have this issue 
- 4.11-rc1 **has** this issue
- 4.12 still has this issue

So I started suspecting that it might be a bug of the kernel itself, which was introduced somewhere in between 4.10 and 4.11-rc1 and is not fixed even in 4.12 yet.

**Comment by opcm** [comment]
@soramichi : thanks a lot for testing! I really appreciate it because I don't have bandwidth to test different kernel versions. As you point out this seems to be a kernel bug.. I will keep this issue open for now (please keep me in the loop).

**Comment by opcm** [comment]
@soramichi : could you please collect strace logs from the working and "broken" kernels?
strace -f -o trace.txt ./pcm.x -i=2

**Comment by soramichi** [comment]
@opcm Sure, I'll do it in during the coming weekend.

**Comment by soramichi** [comment]
@opcm I retrieved straces from the broken kernel and the working kernel:
- [trace_works_nopid.txt](https://github.com/opcm/pcm/files/1185738/trace_works_nopid.txt)
- [trace_broken_nopid.txt](https://github.com/opcm/pcm/files/1185739/trace_broken_nopid.txt)

At a glance, I couldn't see any meaningful difference between the two. I'm still working on bisection searching between 4.10 and 4.11-rc1, so I'll let you know if I find something.

**Comment by opcm** [comment]
@soramichi is there any update? Did you test with the latest kernel? I hope the issue got resolved in the kernel

**Comment by soramichi** [comment]
@opcm Hi, sorry for being not active.

I tried with the latest kernel (4.14.1) on the same hardware, and pcm.x and pcm-core.x successfully measured the cycles and the IPC. So I close this issue.
