### ISSUE TITLE
pcm.x, pcm-memory.x have inconsistent behavior when reporting to CSV

### ISSUE THREAD

**Issue by rodorad** [opcm/pcm#46]
When pcm-memory.x is reporting metrics to csv file you have two headers
1. socket header, telling this stat is for X socket
  - header will have skX where X is the corresponding socket.
   Looks something like this
   ```
    ;;SKT0;SKT0;SKT0;SKT0;SKT0;SKT0;SKT0;SKT0;SK
    ```
2. The data header, telling you what data is reported in the column

when pcm.x is reporting metrics to csv file you also have two headers
1. socket header, telling this stat is for X socket
  -  The socket header lines are empty if they repeat
  looks something like this
```
System;;;;;;;;;;;;;;;;;;;;;;System Core C-States;;;;;System Pack C-States;;;;;;Socket0;;;;;;;;;;;;;;;;Socket1;;;;;;;;;;;;;;;;S
```
2. The data header, telling you what data is reported in the column

The Issue:

I need consistency. I would rather have the socket/system header repeat over and over even if it's a repeat header because it involves less over head on my part.

**Comment by SilverSoldier** [comment]
@opcm I also happen to need this feature. Will you accept a PR for this?

**Comment by opcm** [comment]
@SilverSoldier yes, please submit a PR for review

**Comment by opcm** [comment]
resolved in https://github.com/opcm/pcm/pull/240
