### ISSUE TITLE
Windows .exe files depend on MSVCP140.dll

### ISSUE THREAD

**Issue by RobertCElliott** [opcm/pcm#51]
The Windows binaries on https://ci.appveyor.com/project/opcm/pcm/build/artifacts result in this error on a clean Windows system:

pcm-memory.exe - System Error
The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem.

That is apparently looking for Visual C++ Redistributable for Visual Studio 2015.  However, there is no .msi installer program to help distribute the necessary DLLs.  Perhaps there is there a compiler option to make these .exe files work on their own?

**Comment by opcm** [comment]
I think there is an option for static compilation but then the binaries will get big and no re-use of the MSFT libraries will be possible with other applications. One can just install the redistributable to fix the issue: https://www.microsoft.com/en-us/download/details.aspx?id=48145
I will put the link in the README.
