### ISSUE TITLE
Windows binaries need (signed) msi.sys

### ISSUE THREAD

**Issue by RobertCElliott** [opcm/pcm#52]
The Windows binaries on https://ci.appveyor.com/project/opcm/pcm/build/artifacts are just the pcm*.exe files.  msr.sys file is another binary that is required - and it probably needs to be signed, since it is a driver.

**Comment by opcm** [comment]
If you are not able to sign or test sign drivers on your own please use WinRing0 drivers. Right now nobody from the team has permission or bandwidth to provide (signed) binary drivers.
