### ISSUE TITLE
windows_howto.rtf not displaying correctly (encoding issue?)

### ISSUE THREAD

**Issue by mikehenninger** [opcm/pcm#59]
github shows the raw as a mess of formatting; if you download and open the .rtf with wordpad, it shows the html of the github page.

The way it seems to work is to copypasta the github raw into a plain text document that you rename with the .rtf extension.

I might be doing something dumb here, but this computer is basically fresh out of the box and the howto isn't "just working" for it, so it seems to be a bug in at least some sense.

**Comment by opcm** [comment]
Hi,
if you clone or download the repo the file should be openable with the wordpad. I replaced the link in the readme to raw: https://raw.githubusercontent.com/opcm/pcm/master/WINDOWS_HOWTO.rtf
