### ISSUE TITLE
Support the monitoring of branch misses

### ISSUE THREAD

**Issue by GHScan** [opcm/pcm#62]
Hi Developers,

I'm wondering if there is any plan to support the monitoring of branch misses? It would be great if there is a function like getBranchMisses() since it's really a critical metric to anyone who cares performance.

Thanks

**Comment by opcm** [comment]
all available hardware PMU counters are already occupied with other events in the default mode of PCM. You can collect your own events using pcm-core.x utility or using the custom event programming API (https://github.com/opcm/pcm/blob/master/pcm-core.cpp#L447).

**Comment by GHScan** [comment]
Thanks for your reply, I'll take a look.

**Comment by opcm** [comment]
addressed by pcm-core, pcm-raw and PCM API
