### ISSUE TITLE
Support for Intel Coffee Lake processor

### ISSUE THREAD

**Issue by solracblog** [opcm/pcm#63]
Developers,

When I am using this tool on Linux I get the message:
Unsupported processor model (158).

Is there already support (or an workaround) by someone for the Intel Coffee Lake processors? More specific in my case:
Model: 158
Model name:  Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

Cheers,

Carlos

**Comment by opcm** [comment]
pcm.x should already support your CPU model (https://github.com/opcm/pcm/blob/master/cpucounters.h#L849). Which utility did you test?

**Comment by opcm** [comment]
please let me know if you still have the issue. Otherwise I will close the issue

**Comment by opcm** [comment]
your processor does not have the hardware performance monitoring unit that pcm-power utility requires. It is available only on server processors.
