### ISSUE TITLE
How could I use "memoptest" to do UPI stress and make the total percentage of UPI bandwidth up to 100% ?

### ISSUE THREAD

**Issue by WisQTuser** [opcm/pcm#64]
Hi Developers,
     I'd like to use PCM Tools to monitor UPI traffic and execute UPI stress on my server. There are two processors (Intel Xeon Gold 5115 2.4GHz) and 16 x 8 GB DDR4 2400 on my server.
     I use ./pcm.x to launch the UPI monitor, and use "numactl --cpunodebind=0 --membind=1 ./memoptest 2" "numactl --cpunodebind=1 --membind=0 ./memoptest 2  to run memory bandwidth test.
![memoptest](https://user-images.githubusercontent.com/35085056/37382096-ccb52152-277b-11e8-9b8e-0c0536e67fc0.jpg)

     I have some questions that need your help.
Q1. When I use this two commands to run memory bandwidth test, the pcm.x show some data numbers in UPI0 and UPI1 columns. What's the meaning about 13G and 55% ?
Q2. If the 55% is the total Percentage of UPI bandwidth, how could I do to make the UPI bandwidth up to 100% ? 
![stress](https://user-images.githubusercontent.com/35085056/37382110-e1a9de0e-277b-11e8-9dcd-4cd1d5d2240e.jpg)

Thanks.

**Comment by opcm** [comment]
memoptest is single threaded. A single thread can not consume the whole bandwidth capacity. Please try to run many memoptest processes in parallel to get close to 100% utilization.

**Comment by WisQTuser** [comment]
Hi Developers,
I try to run many memoptest process in parallel, but the result is the same as before. The bandwidth of streaming to memory will be divided equally. please refer the screenshot result as below.

![four windows](https://user-images.githubusercontent.com/35085056/37579623-3ed2ff3c-2b7a-11e8-8fda-ec42f550b093.jpg)

![six windows](https://user-images.githubusercontent.com/35085056/37579631-490c0ca0-2b7a-11e8-82ac-b5596e99b134.jpg)

**Comment by opcm** [comment]
Hi, could you please try to use many memoptest instances but with **read-only** traffic to drive the utilization up? This will be option "0" instead of "1".

It is also important to disable compiler optimizations with "-O0" option:

`g++ -O0 -std=c++11 memoptest.cpp  -o memoptest `

**Comment by WisQTuser** [comment]
Hi Developers,
I follow your suggestions using many memoptest instances with read-only traffic and disable compiler optimizations. The total UPI bandwidth percentage is up to about 85% but still can't get to 100%. If I keep opening a new window to run memoptest with option "0", the reading memory bandwidth will drop down to 17XX MB/s as the below picture . Is there anything that I can do ? Please refer the picture of test result. Thanks.
![intel upi stress up to 85](https://user-images.githubusercontent.com/35085056/37637054-8fbef286-2c40-11e8-8fad-c822441270d7.jpg)

**Comment by opcm** [comment]
Can you try to use a mix of read and write traffic? There is also a specialized tool that can trigger different traffic patterns: https://software.intel.com/en-us/articles/intelr-memory-latency-checker
Options are --bandwidth_matrix and -Wn, where n is the type of traffic

**Comment by WisQTuser** [comment]
Hi Developers,
I try to use Intel memory latency checker to trigger different traffic patterns, and use options --bandwidth_matrix -Wn, where n is 2. But the total UPI bandwidth percentage can't always stay in high performance. Once the Numa mode number appears, the UPI bandwidth percentage will rise to 5X%. After two seconds, the UPI bandwidth percentage will drop to a lower value(0%). How should I do to keep the UPI bandwidth on the highest percentage like the memptest?

![2](https://user-images.githubusercontent.com/35085056/37896615-c30d1746-3116-11e8-932a-652f3b69665d.jpg)

**Comment by opcm** [comment]
could you please increase the test phase duration? I believe this is -t option

**Comment by WisQTuser** [comment]
Hi Developers,
I increase the test phase duration -t, but the result is the same. Still can't keep the UPI bandwidth on the highest percentage.
![t](https://user-images.githubusercontent.com/35085056/37951123-e509fb54-31cd-11e8-8aea-1389f8ee71ac.jpg)

**Comment by WisQTuser** [comment]
Hi developers,
Should I try another methods or command that can trigger the UPI traffic to 100%?

**Comment by opcm** [comment]
the parameter value you have chosen is in seconds. According to the screen shot it still runs local memory test. Did it ever finish? Please choose a smaller value (e.g. 16 seconds (per matrix element))

**Comment by WisQTuser** [comment]
Hi developers,
I use a smaller value to run the test. But the situation is the same as before. Still can't trigger the UPI traffic to 100%. The stress test only run the specific matrix will trigger the bandwidth higher, maybe about 90%. The whole test will be finished in about five minutes. I want the stress can be keep the UPI bandwidth on 100% overnight or even longer.
![mlc_1](https://user-images.githubusercontent.com/35085056/38657841-ea4c3aa8-3e54-11e8-8480-29040aa1b9c9.jpg)
![mlc_2](https://user-images.githubusercontent.com/35085056/38657843-efc3d856-3e54-11e8-9089-db606e95b56a.jpg)
![mlc_3](https://user-images.githubusercontent.com/35085056/38657848-f460f088-3e54-11e8-86c6-a1f89c859dc8.jpg)

**Comment by opcm** [comment]
I could get 96% utilization with these parameters:

`--loaded_latency -omlc_2s_10c_ro-remote.cfg -d0  -t1000`

with this config file (mlc_2s_10c_ro-remote.cfg)

```
0-9 R seq 300000 dram 1
28-37 R seq 300000 dram 0
```

I guess on your 10 core CPU you need to change it to


```
0-9 R seq 300000 dram 1
10-19 R seq 300000 dram 0
```

you can increase -t parameter as you want to run it longer

**Comment by WisQTuser** [comment]
Hi developers,
I follow your instruction to run the test, only get about 60% utilization.
Is there anything wrong with my command or config file?
![mlc_4](https://user-images.githubusercontent.com/35085056/38722621-058304f0-3f31-11e8-80b1-9c8fa75ccf1b.jpg)

**Comment by opcm** [comment]
could you please run mlc without parameters and post the mlc output here as text? (just want to see if you platform configuration is healthy)

**Comment by opcm** [comment]
/proc/cpuinfo is also interesting to check

**Comment by opcm** [comment]
You have a very weird OS processor -> socket topology (round robin). I did not expect that. Here is a fixed configuration file:

```
0,2,4,6,8,10,12,14,16,18 R seq 300000 dram 1
1,3,5,7,9,11,13,15,17,19 R seq 300000 dram 0
```

**Comment by WisQTuser** [comment]
Hi Developers,
After I use the fixed configuration file, I could get about 90% utilization. May I ask what's the meaning about the configuration file and the command "--loaded_latency -omlc_2s_10c_ro-remote.cfg -d0 -t1000? Could I change some value that can get more utilization? Thanks for your support again.
![90](https://user-images.githubusercontent.com/35085056/38854021-b2c17f20-4251-11e8-99de-064654067247.jpg)

**Comment by opcm** [comment]
the options and configuration file format are described the readme file in the mlc package. You might try other traffic types and/or random traversal patterns.

**Comment by opcm** [comment]
the formula you are using gives a somewhat pessimistic estimation of Intel UPI max throughput. Intel UPI may achieve a better packing of data into packets. PCM uses a more optimistic _estimation_ of max throughput assuming _good_ data packing.

**Comment by WisQTuser** [comment]
So if now I have to test with the max throughout of Intel UPI, which standard can I refer to that I could judge the result is passed or failed? Now I can use the command to trigger the total UPI bandwidth to 93%, I just want to know if the 93% of UPI bandwidth reach the standard or not.

**Comment by opcm** [comment]
as far as I know there is no standard that defines the theoretical maximum. It is workload dependent.

**Comment by WisQTuser** [comment]
Thanks for your answer. So you means the percentage of UPI bandwidth can be up to 100% if increasing the workload, how can I increase the workload if I can change hardware configuration or another traffic types?

**Comment by WisQTuser** [comment]
Hi Developers,
You means the percentage of UPI bandwidth can be up to 100% if increasing the workload, how can I increase the workload if I can change hardware configuration or another traffic types?

**Comment by opcm** [comment]
I never managed to drive the utilization to 100%. I think a specific synthetic test is required but I don't know  how to implement it.
