### ISSUE TITLE
Built pcm using visual studio 

### ISSUE THREAD

**Issue by gggh000** [opcm/pcm#73]
I Built pcm using visual studio 15 running on ws2012. The build was successful and executable generated on x64/debug folder however when executing, dll error message: 

Starting MSR service failed with error 2 The system cannot find the file specified.
Trying to load winring0.dll/winring0.sys driver...
Failed to load winring0.dll/winring0.sys driver.

Cannot access CPU counters
You must have signed msr.sys driver in your current directory and have administrator rights to run this program
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).

**Comment by opcm** [comment]
these libraries are not provided with PCM. as described in PCM Windows HOWTO please download them separately.

**Comment by gggh000** [comment]
Looks like there WINDOWS_HOWTO.rtf in which says build msr.sys using winddk.
Is there any steps to it? 

Building using nmake included in VS resulted in following:

c:\dw\pcm\WinMSRDriver\Win7>mymake.bat
c:\dw\pcm\WinMSRDriver\Win7>set BUILD_PATH=
c:\dw\pcm\WinMSRDriver\Win7>rmdir /S /Q objfre_win7_amd64
The system cannot find the file specified.
c:\dw\pcm\WinMSRDriver\Win7>nmake
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.
makefile(1) : fatal error U1052: file '\makefile.def' not found
Stop.
c:\dw\pcm\WinMSRDriver\Win7>rem chdir objfre_win7_amd64\amd64
c:\dw\pcm\WinMSRDriver\Win7>rem copy msr.sys c:\
c:\dw\pcm\WinMSRDriver\Win7>rem chdir ..
c:\dw\pcm\WinMSRDriver\Win7>rem chdir ..

Thanks.,

**Comment by opcm** [comment]
ok. this needs to be debugged. Does the winring driver option work for you?

**Comment by gggh000** [comment]
I am not sure what winring driver option is so I dont know what to do in that case. Please note that I completely clueless and unfamiliar with this this tool and only depending on HOW TO docs. Can you give precise directions?

**Comment by gggh000** [comment]
Ok I found winring mentioned on Windows how to, will try out. thx.

**Comment by gggh000** [comment]
Downloaded one of the mentioned tool and copied all 4 mentioned drivers to c:\windows\system32. Still did not work, so I rebooted and ran it with administrator access however it complained about not finding the winring driver. 

However, I managed to build on linux first try so it appears to be working. Windows build is then less important but may still be nice to have it work in case.
Thanks.,

**Comment by opcm** [comment]
Copying to to c:\windows\system32 is not enough. As described in the how to please
copy WinRing0.dll, WinRing0.sys, WinRing0x64.dll, WinRing0x64.sys files into the PCM.exe binary location.

**Comment by opcm** [comment]
Building the driver should work using the project file: MSR.vcxproj

**Comment by opcm** [comment]
please let me know if the issue is still there (e.g. when you use MSR.vcproj)

**Comment by opcm** [comment]
please reopen if the issue still exists
