### ISSUE TITLE
Build in VS 2017 fails

### ISSUE THREAD

**Issue by scalectrix** [opcm/pcm#75]
- when updating projects to VS 2017 there are dozens of errors (issues with clr ...)
- when leaving the projects untouched "Release" target compiles fine; "Debug" target needs manual modifications (project properties ...) in order to make it compile

**Comment by opcm** [comment]
I don't have VS2017 yet, once I will have it installed later when I will have time I will look into it (not sure when it will happen :-( . Could you please submit the changes to project files in a pull request?

**Comment by scalectrix** [comment]
sorry, missed your reply in July 
Glad it's now fixed
