### ISSUE TITLE
k1om-mpss-linux error: 'struct perf_event_attr' has no member named 'config1'

### ISSUE THREAD

**Issue by leonard-psu** [opcm/pcm#78]
Hello, 
I'm trying to compile for k1om-mpss-linux environment and I get the following error messages:

cpucounters.cpp: In member function 'PCM::ErrorCode PCM::program(PCM::ProgramMode, const void*)':
cpucounters.cpp:2100:23: error: 'struct perf_event_attr' has no member named 'config1'
                     e.config1 = pExtDesc->OffcoreResponseMsrValue[0];
                       ^
cpucounters.cpp:2102:23: error: 'struct perf_event_attr' has no member named 'config1'
                     e.config1 = pExtDesc->OffcoreResponseMsrValue[1];
                       ^
Makefile:65: recipe for target 'cpucounters.o' failed
make: *** [cpucounters.o] Error 1

My environment is defined by using:
source /opt/mpss/3.8.4/environment-setup-k1om-mpss-linux 

Is PCM supported within k1om-mpss-linux environment? If so, can you suggest how to fix? 
Thanks in advance.

**Comment by opcm** [comment]
I don't have access to this environment. As a workaround you can disable the usage of perf in PCM Makefile. comment out the line with "-DPCM_USE_PERF". Please let me know if it solves the issue.

**Comment by opcm** [comment]
please let me know if the suggested workaround works for you

**Comment by lycheenice** [comment]
I have familiar issue, and this work for me. Thanks!

**Comment by opcm** [comment]
closing since the workaround works
