### ISSUE TITLE
macos automatic installation fails

### ISSUE THREAD

**Issue by pavelkucera** [opcm/pcm#82]
Hi,

On Macos Mojave the installation instructions lead to an error. Namely, when `sudo sh ./kextload.sh` calls `cp -R kextbuild/Release/PcmMsrDriver.kext /tmp/.` the file `PcmMsrDriver.kext` is not found.

When I run `make kext`, the file gets build. I believe the issue is that when calling `make kext library`, the build step for library overwrites the generated kext file - I was able to install pcm manually when I backed the kext file before running `make library`.

I think that a sufficient fix would be to let xcodebuild operate in different directories.

Cheers,
Pavel

**Comment by opcm** [comment]
thanks for reporting this. We will address it soon

**Comment by opcm** [comment]
this has been addressed in the latest version of the master branch. Closing the issue.

**Comment by pavelkucera** [comment]
Thank you!
