### ISSUE TITLE
Unsupported processor model (158) Intel i7-7820HQ

### ISSUE THREAD

**Issue by anurag-daware** [opcm/pcm#89]
**CPU Info**
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz

**pcm-power log**
 Processor Counter Monitor  (2018-11-06 11:29:12 +0100 ID=769c8dd)

 Power Monitoring Utility
Number of physical cores: 4
Number of logical cores: 8
Number of online logical cores: 8
Threads (logical cores) per physical core: 2
Num sockets: 1
Physical cores per socket: 4
Core PMU (perfmon) version: 4
Number of core PMU generic (programmable) counters: 4
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 3
Width of fixed counters: 48 bits
Nominal core frequency: 2900000000 Hz
Package thermal spec power: 45 Watt; Package minimum power: 0 Watt; Package maximum power: 0 Watt;
Unsupported processor model (158).
Cleaning up

**Comment by opcm** [comment]
Hi,

you have the same issue as https://github.com/opcm/pcm/issues/60
(Kaby Lake client CPU does not have hardware that is required for pcm-power utility).
