### ISSUE TITLE
VS2010 Toolset not available

### ISSUE THREAD

**Issue by Skysnakes** [opcm/pcm#9]
Hi, 

I tried to compile the project with VS2010. I used the pcm-all.sln file to load the project and used the release build.

When I tried to compile it, I got the following error:

> Specified platform toolset (v110) is not installed or invalid. Please make sure that a supported PlatformToolset value is 

To fix this problem I have to perform the following tasks:

-Select all the subprojects in the project overview with shift
-Right click on one project
-Select Properties
-Select Configuration Properties
-General
-Platform Toolset
-Choose one of the available versions

**Comment by opcm** [comment]
could you please submit your sln file for VS2010 (as "pcm-all-vs2010.sln") or send it to me such that I can upload it to the repository?
